
[[example-encodings-for-tilesetmetadata-informative]]
[appendix,obligation="informative"]
== Example encodings for TileSetMetadata

This informative Annex provides an example of use for _TileSetMetadata_
and _TileMatrixSetLimits_ data structures.

The _TileSetMetadata_ data structure can be used for a resource to
specify the tiling scheme supported by a particular tile set, as well
as additional metadata.

The _TileMatrixSetLimits_ data structure is populated to indicate
that the resource is only available in a fragment of the tiled space.

[[json-document-instance-using-tilesetmetadata]]
=== Example JSON encoding of TileSetMetadata

This example illustrates a TileSetMetadata instance encoded in JSON.

[source,json]
----
include::../schemas/tms/2.0/json/examples/tileset/tiles.WebMercatorQuad.json[]
----

[[json-schema-used-to-validate-the-previous-json-document]]
=== TileSetMetadata JSON Schema

The TileSetMetadata data structure can be included the definition
of an API that provides tiles.
This JSON Schema can be used in an API definition in JSON format and
to validate the previous JSON example.

[source,json]
----
include::../schemas/tms/2.0/json/tileSet.json[]
----

=== TileMatrixSetLimits JSON Schema

This JSON Schema is referenced by the TileSetMetadata schema to define
limits for each tile matrix.

[source,json]
----
include::../schemas/tms/2.0/json/tileMatrixLimits.json[]
----

[[xml-document-instance-using-tilesetmetadata]]
=== Example XML encoding of TileSetMetadata

This example illustrates a TileSetMetadata instance encoded in XML.

[source,xml]
----
include::../schemas/tms/2.0/xml/examples/tileset/tiles.WebMercatorQuad.xml[]
----

[[xml-schema-used-to-validate-the-previous-xml-document]]
=== TileSetMetadata XML Schema
This XML Schema can be used to validate the previous XML example.

[source,xml]
----
include::../schemas/tms/2.0/xml/tileset.xsd[]
----

=== TileMatrixSetLimits XML Schema
This XML Schema is referenced by the TileSetMetadata schema to define
limits for each tile matrix.

[source,xml]
----
include::../schemas/tms/2.0/xml/tilematrixlimits.xsd[]
----
