[appendix]
:appendix-caption: Annex
== Conformance Class Abstract Test Suite (Normative)

////
[NOTE]
Ensure that there is a conformance class for each requirements class and a test for each requirement (identified by requirement name and number)

=== Conformance Class A

==== Requirement 1
[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/req-name-1
|Requirement: |/req/req-class-a/req-name-1
|Test purpose: | Verify that...
|Test method: | Inspect...
|===

==== Requirement 2
////

A TileMatrixSet implementation of this standard must satisfy the following system characteristics to be conformant with this specification.

[[a.1-conformance-class-tilematrixset2d]]
=== Conformance class: TileMatrixSet2D

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/tilematrixset2d

Tests identifiers below are relative to http://www.opengis.net/spec/tilematrixset/2.0

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *conf/tilematrixset2d/model*
| Test Purpose: | *Req 1 req/tilematrixset2d/model:* +
A tile matrix set 2D _shall_ be defined following the UML model as shown in Figure 1 and the model description in Table 1 and Table 2. +
| Dependency: | http://www.opengis.net/spec/owscommon/2.0/req
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSet2D instances point to the TileMatrixSet2D data type definition and follow the data model specified in Table 1 and Table 2 and its dependencies.
|===

[[a.2-conformance-class-variablematrixwidth]]
=== Conformance class: VariableMatrixWidth

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/variablematrixwidth

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *variablematrixwidth/model*
| Test Purpose: | *Req 5 req/variablematrixwidth/model:* +
When a tiled resource or dataset has variable width tiles, the resource __ or dataset _shall_ define the variable matrix width in a tile matrix set 2D using a variablematrixwidth data structure. This will result in the following UML model shown in Figure 9 and model description in Table 6.**
| Test method: | Validate the requirements of the model

Test passes if VariableMatrixWidth instances point to the VariableMatrixWidth data type definition and follow the data model specified in Table 6 and its dependencies.
|===

==== Identifier
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *variablematrixwidth/coalescence1*
| Test Purpose: | *Req 6 req/variablematrixwidth/coalescence1:* +
Only the tile rows will with coalesces factor different of one shall be encoded. It a tile row is not mentioned in the variablematrixwidth description a coalesce factor of 1 shall be considered for that row.**
| Test method: | Validate the requirements of the model

Test passes if all VariableMatrixWidth elements in the instance has a coalescence factor bigger than 1.
|===

[[a.3-conformance-class-json-encoding-for-tilematrixset2d]]
=== Conformance class: JSON Encoding for TileMatrixSet2D

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/json-tilematrixset2d

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixset2d/model*
| Test Purpose: | *Req 16 req/xml-tilematrixset2d/model:* +
A TileMatrixSet2D encoded in XML _shall_ implement the class TileMatrixSet2D +
| Dependency: | req/tilematrixset2d.
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSet2D instances follow the data model specified in Table 1 and Table 2 and its dependencies.
|===

==== IETF
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixset2d/ietf*
| Test Purpose: | *Req 17 req/json-tilematrixset2d/ietf:* +
A TileMatrixSet2D encoded in JSON _shall_ conform to IETF RFC7159****
| Test method: | Validate the requirements of the IETF

Test passes if TileMatrixSet2D JSON instances pass format validation against the IETF rules.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixset2d/schema*
| Test Purpose: | *Req 18 req/json-tilematrixset2d/schema:* +
A TileMatrixSet2D encoded in JSON _shall_ validate using the JSON schema for a tile matrix set 2D.**
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSet2D JSON instances pass validation against the tile matrix set 2D JSON Schemas.
|===

==== Media type
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixset2d/media-type*
| Test Purpose: | *Req 19 req/json-tilematrixset2d/media-type:* +
A TileMatrixSet2D encoded in an independent JSON document _shall_ use the media type application/json.**
| Test method: | Validate the requirements of the media type

Test passes if the independent instances of TileMatrixSet2D are exposed as application/json media type.
|===

[[a.4-conformance-class-json-encoding-for-variablematrixwidth]]
=== Conformance class: JSON Encoding for VariableMatrixWidth

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/json-variablematrixwidth

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-variablematrixwidth/model*
| Test Purpose: | *Req 26 req/json-variablematrixwidth/model:* +
A VariableMatrixWidth encoded in JSON _shall_ implement the class VariableMatrixWidth +
| Dependency: | req/variablematrixwidth +
| Dependency: | req/json-tilematrixset2d.
| Test method: | Validate the requirements of the model

Test passes if VariableMatrixWidth instances follow the data model specified in Table 6 and its dependencies.
|===

==== IETF
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-variablematrixwidth/ietf*
| Test Purpose: | *Req 27 req/json-variablematrixwidth/ietf:* +
A VariableMatrixWidth encoded in JSON _shall_ conform to IETF RFC7159****
| Test method: | Validate the requirements of the IETF rules

Test passes if VariableMatrixWidth JSON instances pass format validation against the IETF rules.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-variablematrixwidth/schema*
| Test Purpose: | *Req 28 req/json-variablematrixwidth/schema:* +
A VariableMatrixWidth encoded in JSON _shall_ validate using the JSON schema for a variable matrix width.**
| Test method: | Validate the requirements of the schema

Test passes if VariableMatrixWidth JSON instances pass validation against the variable matrix width JSON Schemas.
|===


[[a.5-conformance-class-xml-encoding-for-tilematrixset2d]]
=== Conformance class: XML Encoding for TileMatrixSet2D

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/xml-tilematrixset2d

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixset2d/model*
| Test Purpose: | *Req 7 req/xml-tilematrixset2d/model:* +
A TileMatrixSet2D encoded in XML _shall_ implement the class TileMatrixSet2D +
| Dependency: | req/tilematrixset2d.
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSet2D instances use a TileMatrixSet2D XML data type definition that follows the data model specified in Table 1 and Table 2 and its dependencies.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixset2d/schema*
| Test Purpose: | *Req 8 req/xml-tilematrixset2d/schema:* +
A TileMatrixSet2D encoded in XML _shall_ validate using the XML schema for a tile matrix set 2D.**
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSet2D XML instances pass validation against the tile matrix set 2D XML Schemas.
|===

==== Media type
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixset2d/media-type*
| Test Purpose: | *Req 9 req/json-tilematrixset2d/media-type:* +
A TileMatrixSet2D encoded in an independent JSON document _shall_ use the media type application/json.**
| Test method: | Validate the requirements of the media type

Test passes if the independent instances of TileMatrixSet2D are exposed as application/xml MIME type.
|===

[[a.6-conformance-class-xml-encoding-for-variablematrixwidth]]
=== Conformance class: XML Encoding for VariableMatrixWidth

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/xml-variablematrixwidth

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-variablematrixwidth/model*
| Test Purpose: | *Req 12 req/xml-tilematrixsetlimits2d/model:* +
A TileMatrixSetMetadata encoded in XML _shall_ implement the class TileMatrixSetMetadata +
| Dependency: | req/tilematrixsetmetadata +
| Dependency: | req/xml-tilematrixsetlimits2d.
| Test method: | Validate the requirements of the model

Test passes if VariableMatrixWidth instances use a VariableMatrixWidth XML data type definition that follows the data model specified in Table 6 and its dependencies.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-variablematrixwidth/schema*
| Test Purpose: | *Req 13 req/xml-tilematrixsetmetadata/schema:* +
A TileMatrixSetMetadata encoded in XML _shall_ validate using the XML schema for a tile matrix set link 2D.**
| Test method: | Validate the requirements of the model

Test passes if VariableMatrixWidth XML instances pass validation against the variable matrix width XML Schemas.
|===


[[a.7-conformance-class-tilematrixsetlimits2d]]
=== Conformance class: TileMatrixSetLimits2D

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/tilematrixsetlimits2d

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *tilematrixsetlimits2d/model*
| Test Purpose: | *Req 2 req/tilematrixsetlimits2d/model:* +
A tile matrix set limits 2D _shall_ be defined following the UML model as shown in Figure 7 and model description in Table 3 and Table 4. +
| Dependency: | http://www.opengis.net/spec/owscommon/2.0/req
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetLimits2D instances point to the TileMatrixSetLimits2D data type definition and follow the data model specified in Table 3 and Table 4 and its dependencies.
|===

[[a.8-conformance-class-tilematrixsetmetadata]]
=== Conformance class: TileMatrixSetMetadata

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/tilematrixsetmetadata

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *tilematrixsetmetadata/identifier*
| Test Purpose: | *Req 3 req/tilematrixsetmetadata/identifier:* +
A tiled resource or dataset _shall_ declare support to a tile matrix set 2D by link to a tile matrix set definition by citing a tile matrix set identifier defined in the same document instance or an active (resolvable) link to a TileMatrixSet definition in an external document.**
| Test method: | Validate the requirements of the model

Test passes if all TileMatrixSetMetadata elements in the instance cite a tile matrix set by mentioning at least one TileMatrixSet identifier or by using a URI that can be resolved into a TileMatrixSet2D.
|===

==== Identifier
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *tilematrixsetmetadata/model*
| Test Purpose: | *Req 4 req/tilematrixsetmetadata/model:* +
When a tiled resource or dataset has tiles available only for a region or regions of the complete tiled space, the resource __ or dataset _shall_ declare partial support to a tile matrix set 2D using one or more __ tile matrix set limits data structures. This will result in the following  UML model shown in Figure 7 and model description in Table 5. +
| Dependency: | req/tilematrixsetlimits
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetMetadata instances point to the TileMatrixSetMetadata data type definition and follow the data model specified in Table 5 and its dependencies.
|===

[[a.9-conformance-class-json-encoding-for-tilematrixsetlimits2d]]
=== Conformance class: JSON Encoding for TileMatrixSetLimits2D

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/json-tilematrixsetlimits2d

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixsetlimits2d/model*
| Test Purpose: | *Req 20 req/json-tilematrixsetlimits2d/model:* +
A TileMatrixSetLimits2D encoded in JSON _shall_ implement the class TileMatrixSetLimits2D +
| Dependency: | req/tilematrixsetlimits2d.
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetLimits2D instances follow the data model specified in Table 3 and Table 4 and its dependencies.
|===

==== IETF
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixsetlimits2d/ietf*
| Test Purpose: | *Req 21 req/json-tilematrixsetlimits2d/ietf:* +
A TileMatrixSetLimits2D encoded in JSON _shall_ conform to IETF RFC7159****
| Test method: | Validate the requirements of the IETF

Test passes if TileMatrixSetLimits2D JSON instances pass format validation against the IETF rules.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixsetlimits2d/schema*
| Test Purpose: | *Req 22 req/json-tilematrixsetlimits2d/schema:* +
A TileMatrixSetLimits2D encoded in JSON _shall_ validate using the JSON schema for a tile matrix set limits 2D.**
| Test method: | Validate the requirements of the schema

Test passes if TileMatrixSetLimits2D JSON instances pass validation against the tile matrix set limits 2D JSON Schemas.
|===

[[a.10-conformance-class-json-encoding-for-tilematrixsetmetadata]]
=== Conformance class: JSON Encoding for TileMatrixSetMetadata

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/json-tilematrixsetmetadata

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixsetmetadata/model*
| Test Purpose: | *Req 23 req/json-tilematrixsetmetadata/model:* +
A TileMatrixSetLimits2D encoded in JSON _shall_ implement the class TileMatrixSetMetadata +
| Dependency: | req/tilematrixsetmetadata +
| Dependency: | req/json-tilematrixsetlimits2d.
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetMetadata instances follow the data model specified in Table 5 and its dependencies.
|===

==== IETF
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixsetmetadata/ietf*
| Test Purpose: | *Req 24 req/json-tilematrixsetmetadata/ietf:* +
A TileMatrixSetMetadata encoded in JSON _shall_ conform to IETF RFC7159****
| Test method: | Validate the requirements of the IETF rules

Test passes if TileMatrixSetMetadata JSON instances pass format validation against the IETF rules.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *json-tilematrixsetmetadata/schema*
| Test Purpose: | *Req 25 req/json-tilematrixsetmetadata/schema:* +
A TileMatrixSetMetadata encoded in JSON _shall_ validate using the JSON schema for a tile matrix set link 2D.**
| Test method: | Validate the requirements of the schema

Test passes if TileMatrixSetMetadata JSON instances pass validation against the tile matrix set link 2D JSON Schemas.
|===

[[a.11-conformance-class-xml-encoding-for-tilematrixsetlimits2d]]
=== Conformance class: XML Encoding for TileMatrixSetLimits2D

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/xml-tilematrixsetlimits2d

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixsetlimits2d/model*
| Test Purpose: | *Req 10 req/xml-tilematrixsetlimits2d/model:* +
A TileMatrixSetLimits2d encoded in XML _shall_ implement the class TileMatrixSetLimits2D +
| Dependency: | req/tilematrixsetlimits2d.
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetLimits2D instances point to the TileMatrixSetLimits2D data type definition and follow the data model specified in Table 3 and Table 4 and its dependencies.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixsetlimits2d/schema*
| Test Purpose: | *Req 11 req/ xml-tilematrixsetlimits2d/schema:* +
A TileMatrixSetLimits2D encoded in XML _shall_ validate using the XML schemas for a tile matrix set limits 2D.**
| Test method: | Validate the requirements of the schema

Test passes if TileMatrixSetLimits2D XML instances pass validation against the tile matrix set limits 2D XML Schemas.
|===

[[a.12-conformance-class-xml-encoding-for-tilematrixsetmetadata]]
=== Conformance class: XML Encoding for TileMatrixSetMetadata

The OGC URI identifier of this conformance class is:

http://www.opengis.net/spec/tilematrixset/2.0/conf/xml-tilematrixsetmetadata

==== Model
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixsetmetadata/model*
| Test Purpose: | *Req 12 req/xml-tilematrixsetlimits2d/model:* +
A TileMatrixSetMetadata encoded in XML _shall_ implement the class TileMatrixSetMetadata +
| Dependency: | req/tilematrixsetmetadata +
| Dependency: | req/xml-tilematrixsetlimits2d.**
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetMetadata instances use a TileMatrixSetMetadata XML data type definition that follows the data model specified in Table 5 and its dependencies.
|===

==== Schema
[cols=">20h,<80d",width="100%"]
|===
| Test id: | *xml-tilematrixsetmetadata/schema*
| Test Purpose: | *Req 13 req/xml-tilematrixsetmetadata/schema:* +
A TileMatrixSetMetadata encoded in XML _shall_ validate using the XML schema for a tile matrix set link 2D.**
| Test method: | Validate the requirements of the model

Test passes if TileMatrixSetMetadata XML instances pass validation against the tile matrix set link 2D XML Schemas.
|===

