[appendix]
[[annex_h]]
[[example-encodings-for-variable-matrix-width-informative]]
:appendix-caption: Annex
== Example encodings for Variable Matrix Width (Informative)

This informative Annex provides an example of the Variable Matrix Width extension. In this case, the variable matrix width is applied only to the tile matrix with identifier 3 and 4.

[[xml-document-instance-using-variablematrixwidth]]
=== XML document instance using VariableMatrixWidth

[source,xml]
....
<?xml version="1.0" encoding="UTF-8"?>
<TileMatrixSet id="WorldCRS84Quad" xmlns="http://www.opengis.net/tms/1.0"
xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/tms/1.0 ../tms.xsd">
   <ows:Title>CRS84 for the World</ows:Title>
   <ows:Identifier>WorldCRS84Quad</ows:Identifier>
   <ows:BoundingBox crs="http://www.opengis.net/def/crs/OGC/1.3/CRS84">
      <ows:LowerCorner>-180 -90</ows:LowerCorner>
      <ows:UpperCorner>180 90</ows:UpperCorner>
   </ows:BoundingBox>
   <ows:SupportedCRS>
            http://www.opengis.net/def/crs/OGC/1.3/CRS84
         </ows:SupportedCRS>
   <WellKnownScaleSet>
            http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad
         </WellKnownScaleSet>
   <TileMatrix>
      <ows:Identifier>1</ows:Identifier>
      <ScaleDenominator>279541132.0143589</ScaleDenominator>
      <TopLeftCorner>-180 90</TopLeftCorner>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>2</MatrixWidth>
      <MatrixHeight>1</MatrixHeight>
   </TileMatrix>
   <TileMatrix>
      <ows:Identifier>2</ows:Identifier>
      <ScaleDenominator>139770566.0071794</ScaleDenominator>
      <TopLeftCorner>-180 90</TopLeftCorner>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>4</MatrixWidth>
      <MatrixHeight>2</MatrixHeight>
   </TileMatrix>
   <TileMatrix>
      <ows:Identifier>3</ows:Identifier>
      <ScaleDenominator>69885283.00358972</ScaleDenominator>
      <TopLeftCorner>-180 90</TopLeftCorner>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>8</MatrixWidth>
      <MatrixHeight>4</MatrixHeight>
      <VariableMatrixWidth>
         <Coalesce>2</Coalesce>
         <MinTileRow>0</MinTileRow>
         <MaxTileRow>0</MaxTileRow>
      </VariableMatrixWidth>
      <VariableMatrixWidth>
         <Coalesce>2</Coalesce>
         <MinTileRow>3</MinTileRow>
         <MaxTileRow>3</MaxTileRow>
      </VariableMatrixWidth>
   </TileMatrix>
   <TileMatrix>
      <ows:Identifier>4</ows:Identifier>
      <ScaleDenominator>34942641.50179486</ScaleDenominator>
      <TopLeftCorner>-180 90</TopLeftCorner>
      <TileWidth>256</TileWidth>
      <TileHeight>256</TileHeight>
      <MatrixWidth>16</MatrixWidth>
      <MatrixHeight>8</MatrixHeight>
      <VariableMatrixWidth>
         <Coalesce>4</Coalesce>
         <MinTileRow>0</MinTileRow>
         <MaxTileRow>0</MaxTileRow>
      </VariableMatrixWidth>
      <VariableMatrixWidth>
         <Coalesce>2</Coalesce>
         <MinTileRow>1</MinTileRow>
         <MaxTileRow>1</MaxTileRow>
      </VariableMatrixWidth>
      <VariableMatrixWidth>
         <Coalesce>2</Coalesce>
         <MinTileRow>6</MinTileRow>
         <MaxTileRow>6</MaxTileRow>
      </VariableMatrixWidth>
      <VariableMatrixWidth>
         <Coalesce>4</Coalesce>
         <MinTileRow>7</MinTileRow>
         <MaxTileRow>7</MaxTileRow>
      </VariableMatrixWidth>
   </TileMatrix>
</TileMatrixSet>

....

 

[[json-document-instance-using-variablematrixwidth]]
=== JSON document instance using VariableMatrixWidth

This example takes the first five tile matrices of the definition of the GNOSIS Global Grid (http://ecere.ca/gnosis/) and presents them encoded in JSON following this standard. Please note that GNOSIS Global Grid conforms to the GoogleCRS84Quad well known scale set but it is not using the same identifiers as the WorldCRS84Quad TileMatrixSet. The complete example can be found in the supplemental material described in Annex B.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "GNOSIS for the World",
   "identifier": "GNOSISGlobalGrid",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "lowerCorner":
      [
         -180,
         -90
      ],
      "upperCorner":
      [
         180,
         90
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
   "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad"
   "tileMatrix":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 139770566.0071794390678,
         "topLeftCorner":
         [
           -180,
           -90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 69885283.0035897195339,
         "topLeftCorner":
         [
           -180,
           -90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 4,
         "variableMatrixWidth":
         [
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 0,
              "maxTileRow": 0
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 3,
              "maxTileRow": 3
           }
         ]
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 34942641.501794859767,
         "topLeftCorner":
         [
           -180,
           -90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 8,
         "variableMatrixWidth":
         [
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 4,
              "minTileRow": 0,
              "maxTileRow": 0
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 1,
              "maxTileRow": 1
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 6,
              "maxTileRow": 6
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 4,
              "minTileRow": 7,
              "maxTileRow": 7
           }
         ]
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 17471320.7508974298835,
         "topLeftCorner":
         [
           -180,
           -90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 16,
         "variableMatrixWidth":
         [
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 8,
              "minTileRow": 0,
              "maxTileRow": 0
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 4,
              "minTileRow": 1,
              "maxTileRow": 1
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 2,
              "maxTileRow": 3
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 12,
              "maxTileRow": 13
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 4,
              "minTileRow": 14,
              "maxTileRow": 14
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 8,
              "minTileRow": 15,
              "maxTileRow": 15
           }
         ]
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 8735660.3754487149417,
         "topLeftCorner":
         [
           -180,
           -90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 32,
         "variableMatrixWidth":
         [
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 16,
              "minTileRow": 0,
              "maxTileRow": 0
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 8,
              "minTileRow": 1,
              "maxTileRow": 1
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 4,
              "minTileRow": 2,
              "maxTileRow": 3
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 4,
              "maxTileRow": 7
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 2,
              "minTileRow": 24,
              "maxTileRow": 27
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 4,
              "minTileRow": 28,
              "maxTileRow": 29
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 8,
              "minTileRow": 30,
              "maxTileRow": 30
           },
           {
              "type": "VariableMatrixWidthType",
              "coalesce": 16,
              "minTileRow": 31,
              "maxTileRow": 31
           }
         ]
      }
   ] 
}

....
 
