[appendix]
[[annex-example-encodings-for-variable-matrix-width-informative]]
:appendix-caption: Annex
== Example encodings for Variable Matrix Width TileMatrixSets (Informative)

This informative Annex provides examples of encodings for tile matrix sets using the Variable Matrix Width requirements class.

=== GNOSIS Global Grid

These are the JSON and XML definitions of the GNOSISGlobalGrid tile matrix set (see <<gnosis-global-grid-tilematrixset-definition>>)
that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices
for more detailed scales is possible if they follow the same pattern.

One can define an arbitrary number of zoom levels. Here, 5 zoom levels are illustrated.

[[json-gnosisglobalgrid]]
==== GNOSIS Global Grid (JSON encoding)

The complete JSON example can be found in the supplemental material described in <<annex-schema-documents-normative>>

[source,json]
....
include::../schemas/tms/2.0/json/examples/tilematrixset/GNOSISGlobalGrid.json[lines=1..189]
      }
   ]
}
....

[[xml-gnosisglobalgrid]]
==== GNOSIS Global Grid (XML encoding)

[source,xml]
....
include::../schemas/tms/2.0/xml/examples/tilematrixset/GNOSISGlobalGrid.xml[lines=1..161]
</TileMatrixSet>
....

=== CDB Global Grid

These are the JSON and XML definitions of the CDBGlobalGrid tile matrix set (see <<cdb-global-grid-tilematrixset-definition>>)
that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices
for more detailed scales is possible if they follow the same pattern.

One can define an arbitrary number of zoom levels. Here, 3 zoom levels are illustrated.


[[json-cdbglobalgrid]]
==== CDB Global Grid (JSON encoding)

[source,json]
....
include::../schemas/tms/2.0/json/examples/tilematrixset/CDBGlobalGrid.json[lines=1..18]
include::../schemas/tms/2.0/json/examples/tilematrixset/CDBGlobalGrid.json[lines=604..862]
      }
   ]
}
....
 

[[xml-cdbglobalgrid]]
==== CDB Global Grid (XML encoding)

[source,xml]
....
include::../schemas/tms/2.0/xml/examples/tilematrixset/CDBGlobalGrid.xml[lines=1..12]
include::../schemas/tms/2.0/xml/examples/tilematrixset/CDBGlobalGrid.xml[lines=553..792]
</TileMatrixSet>
....
 