[appendix]
[[example-encodings-for-tilesetmetadata-informative]]
:appendix-caption: Annex
== Example encodings for TileSetMetadata (Informative)

This informative Annex provides an example of use for TileSetMetadata and TileMatrixSetLimits2D data structures.

[[json-document-instance-using-tilesetmetadata]]
=== JSON document instance using TileSetMetadata

TileSetMetadata data structure can be used for a resource to specify the tiling schema the resource supports. Eventually, the resource can only be available in a fragment of the tiled space and to specify that, the TileMatrixSetLimits2D data structure is populated. This example illustrates and instance encoded in JSON.

[source,json]
....
include::../schemas/tms/2.0/json/examples/tileset/tiles.WebMercatorQuad.json[]
....

[[json-schema-used-to-validate-the-previous-json-document]]
=== JSON schema used to validate the previous JSON document

The TileSetMetadata data structure can be included the definition of an API that provides tiles. This JSON Schema can be used in an API definition in JSON format and to validate the previous JSON example.

[source,json]
....
include::../schemas/tms/2.0/json/tileSet.json[]
....

[source,json]
....
include::../schemas/tms/2.0/json/tileMatrixLimits.json[]
....

[[xml-document-instance-using-tilesetmetadata]]
=== XML document instance using TileSetMetadata

TileSetMetadata data structure can be used for a resource to specify the tiling schema the resource supports. Eventually, the resource can only be available in a fragment of the tiled space and to specify that, the TileMatrixSetLimits2D data structure is populated. This example illustrates and instance encoded in XML.

[source,xml]
....
include::../schemas/tms/2.0/xml/examples/tileset/tiles.WebMercatorQuad.xml[]
....

[[xml-schema-used-to-validate-the-previous-xml-document]]
=== XML schema used to validate the previous XML document
This XML Schema can be used to validate the previous XML example.

[source,xml]
....
include::../schemas/tms/2.0/xml/tileset.xsd[]
....

[source,xml]
....
include::../schemas/tms/2.0/xml/tilematrixlimits.xsd[]
....
