[appendix]
[[annex_b]]
[[annex-b-schema-documents-normative]]
:appendix-caption: Annex
== Schema Documents (Normative)

In addition to this document, this standard includes several normative Schema Documents.
These Schema Documents are posted online at the URL http://schemas.opengis.net/tms/2.0.

[[b.1-json-schema]]
=== JSON Schema

The JSON Schema Documents are situated in the json subfolder and are named:

json/tileMatrixSet.json
json/tileMatrixLimits.json
json/tileSet.json

They include the schemas necessary to JSON-validate the classes JSONTileMatrixSet2D, JSONTileMatrixSetLimits2D and JSONTileSetMetadata, respectively.
The json/examples/tilematrixset subfolder is provided with the complete set of JSON documents that are also provided in Annex E and F of this document.
In addition, the directory named:

json/examples/tileset

contains examples of the JSON tileset metadata encodings.

[[b.2-xml-schema]]
=== XML Schema     

The main XML Schema Document is situated in the xml subfolder and it is named:

xml/tilematrixset.xsd
xml/tilematrixlimits.xsd
xml/tileset.xsd

They includes the schemas necessary to XML-validate the classes XMLTileMatrixSet2D, XMLTileMatrixSetLimits2D and XMLTileSetMetadata, respectively.
The xml/examples/tilematrixset subfolder is provided with the complete set of XML documents that are also provided in Annex E and F of this document.
In addition, the directory named:

xml/examples/tileset

contains examples of the XML tileset metadata encodings.
