[appendix]
[[annex_h]]
[[example-encodings-for-variable-matrix-width-informative]]
:appendix-caption: Annex
== Example encodings for Variable Matrix Width TileMatrixSets (Informative)

This informative Annex provides examples of the Variable Matrix Width extension.

The first example shows the first five tile matrices of the definition of the https://ecere.ca/gnosis/[GNOSIS] Global Grid and presents them
encoded in XML and JSON following this standard.
Note that the GNOSIS Global Grid scales match the _GoogleCRS84Quad_ Well Known Scale Set, but starts at the third scale of the set.
Since the _WorldCRS84Quad_ TileMatrixSet starts at the second scale, its TileMatrix identifier 1 is equivalent to the GNOSISGlobalGrid TileMatrix identifier 0,
with the exception of the variable width considerations.
In this case, the variable matrix width is applied only from the tile matrix with identifier 1 and higher.
The GNOSIS Global Grid is easy to implement procedurally: it is a quad-tree starting with 8 90 degrees x 90 degrees tiles at level 0,
with the exception that tiles touching a pole are split into 3 tiles rather than 4 -- the polar portion is not split longitude-wise.
Therefore there will always be only 4 tiles touching each pole.

The complete JSON example can be found in the supplemental material described in Annex B.


[[json-gnosisglobalgrid]]
=== GNOSIS Global Grid (JSON)

[source,json]
....
include::../schemas/tms/2.0/json/examples/tilematrixset/GNOSISGlobalGrid.json[lines=1..183]
      }
   ]
}
....

[[xml-gnosisglobalgrid]]
=== GNOSIS Global Grid (XML)

[source,xml]
....
include::../schemas/tms/2.0/xml/examples/tilematrixset/GNOSISGlobalGrid.xml[lines=1..157]
</TileMatrixSet>
....


The second example represents the https://docs.opengeospatial.org/is/15-113r5/15-113r5.html#CharacteristicsoftheCDBtilingstoragemodel[CDB Zones and Levels of Detail]
which can be encoded following this standard with the use of variable widths.
For the tile matrices with negative identifiers of the CDB Global Grid, the tiles' geographic extents remain the same as those of tile matrix 0,
but the tile size in pixels is reduced. The levels -1 to 2 are shown here.
Note that unlike the GNOSIS Global Grid, for the CDB Global Grid the polar adjustment is the same for all tile matrices of the set.

[[json-cdbglobalgrid]]
=== CDB Global Grid (JSON)

[source,json]
....
include::../schemas/tms/2.0/json/examples/tilematrixset/CDBGlobalGrid.json[lines=1..17]
include::../schemas/tms/2.0/json/examples/tilematrixset/CDBGlobalGrid.json[lines=594..848]
      }
   ]
}
....
 

[[xml-cdbglobalgrid]]
=== CDB Global Grid (XML)

[source,xml]
....
include::../schemas/tms/2.0/xml/examples/tilematrixset/CDBGlobalGrid.xml[lines=1..12]
include::../schemas/tms/2.0/xml/examples/tilematrixset/CDBGlobalGrid.xml[lines=553..791]
</TileMatrixSet>
....
 
