[appendix]
[[annex_e]]
[[annex-e-example-encodings-for-common-tilematrixset2d-informative]]
:appendix-caption: Annex
== Example Encodings for Common TileMatrixSet2D (Informative)

This Annex provides examples of XML and JSON encodings than can be used to define tile matrix sets.

[[e.1-web-mercator-quad-tilematrixset-definition.]]
=== Web Mercator Quad TileMatrixSet definition.

[[e.1.1-web-mercator-quad-tilematrixset-definition.-xml-example.]]
==== Web Mercator Quad TileMatrixSet definition. XML example.

This is the XML definition of the WebMercatorQuad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
   <TileMatrixSet xml:id="WebMercatorQuad">
      <ows:Title>Google Maps Compatible for the World</ows:Title>
      <ows:Identifier>WebMercatorQuad</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/3857">
         <ows:LowerCorner>
            -20037508.3427892 -20037508.3427892
         </ows:LowerCorner>
         <ows:UpperCorner>
             20037508.3427892 20037508.3427892
         </ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
          http://www.opengis.net/def/crs/EPSG/0/3857
      </ows:SupportedCRS>
      <WellKnownScaleSet>
          http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible
      </WellKnownScaleSet>
      <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>559082264.028717</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1</MatrixWidth>
        <MatrixHeight>1</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>279541132.014358</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2</MatrixWidth>
        <MatrixHeight>2</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>139770566.007179</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>69885283.0035897</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>34942641.5017948</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16</MatrixWidth>
        <MatrixHeight>16</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>17471320.7508974</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32</MatrixWidth>
        <MatrixHeight>32</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>8735660.37544871</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>64</MatrixWidth>
        <MatrixHeight>64</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>4367830.18772435</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>128</MatrixWidth>
        <MatrixHeight>128</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>2183915.09386217</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>256</MatrixWidth>
        <MatrixHeight>256</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>1091957.54693108</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>512</MatrixWidth>
        <MatrixHeight>512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>545978.773465544</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1024</MatrixWidth>
        <MatrixHeight>1024</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>272989.386732772</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2048</MatrixWidth>
        <MatrixHeight>2048</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>136494.693366386</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4096</MatrixWidth>
        <MatrixHeight>4096</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>68247.346683193</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8192</MatrixWidth>
        <MatrixHeight>8192</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>34123.6733415964</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16384</MatrixWidth>
        <MatrixHeight>16384</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>17061.8366707982</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32768</MatrixWidth>
        <MatrixHeight>32768</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>16</ows:Identifier>
        <ScaleDenominator>8530.91833539913</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>65536</MatrixWidth>
        <MatrixHeight>65536</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>17</ows:Identifier>
        <ScaleDenominator>4265.45916769956</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>131072</MatrixWidth>
        <MatrixHeight>131072</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>18</ows:Identifier>
        <ScaleDenominator>2132.72958384978</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>262144</MatrixWidth>
        <MatrixHeight>262144</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>19</ows:Identifier>
        <ScaleDenominator>1066.36479192489</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>524288</MatrixWidth>
        <MatrixHeight>524288</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>20</ows:Identifier>
        <ScaleDenominator>533.182395962445</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1048576</MatrixWidth>
        <MatrixHeight>1048576</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>21</ows:Identifier>
        <ScaleDenominator>266.591197981222</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2097152</MatrixWidth>
        <MatrixHeight>2097152</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>22</ows:Identifier>
        <ScaleDenominator>133.295598990611</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4194304</MatrixWidth>
        <MatrixHeight>4194304</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>23</ows:Identifier>
        <ScaleDenominator>66.6477994953056</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8388608</MatrixWidth>
        <MatrixHeight>8388608</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>24</ows:Identifier>
        <ScaleDenominator>33.3238997476528</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16777216</MatrixWidth>
        <MatrixHeight>16777216</MatrixHeight>
      </TileMatrix>
   </TileMatrixSet>

....

 

One can define an arbitrary number of zoom levels. Here, 25 zoom levels are illustrated.

[[e.1.2-web-mercator-quad-tilematrixset-definition.-json-encoding]]
==== Web Mercator Quad TileMatrixSet definition. JSON Encoding

This is the JSON definition of the WebMercatorQuad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "Google Maps Compatible for the World",
   "identifier": "WebMercatorQuad",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/3857",
      "lowerCorner": [-20037508.3427892, -20037508.3427892],
      "upperCorner": [20037508.3427892, 20037508.3427892]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3857",
   "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 559082264.028717,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1,
         "matrixHeight": 1
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 279541132.014358,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 139770566.007179,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 69885283.0035897,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 34942641.5017948,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 17471320.7508974,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 8735660.37544871,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 4367830.18772435,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 2183915.09386217,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 1091957.54693108,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 545978.773465544,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 272989.386732772,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 136494.693366386,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 68247.346683193,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 34123.6733415964,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 17061.8366707982,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 32768
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 8530.91833539913,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 65536,
         "matrixHeight": 65536
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 4265.45916769956,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 131072,
         "matrixHeight": 131072
      },
      {
         "type": "TileMatrixType",
         "identifier": "18",
         "scaleDenominator": 2132.72958384978,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 262144,
         "matrixHeight": 262144
      },
      {
         "type": "TileMatrixType",
         "identifier": "19",
         "scaleDenominator": 1066.36479192489,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 524288,
         "matrixHeight": 524288
      },
      {
         "type": "TileMatrixType",
         "identifier": "20",
         "scaleDenominator": 533.182395962445,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1048576,
         "matrixHeight": 1048576
      },
      {
         "type": "TileMatrixType",
         "identifier": "21",
         "scaleDenominator": 266.591197981222,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2097152,
         "matrixHeight": 2097152
      },
      {
         "type": "TileMatrixType",
         "identifier": "22",
         "scaleDenominator": 133.295598990611,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4194304,
         "matrixHeight": 4194304
      },
      {
         "type": "TileMatrixType",
         "identifier": "23",
         "scaleDenominator": 66.6477994953056,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8388608,
         "matrixHeight": 8388608
      },
      {
         "type": "TileMatrixType",
         "identifier": "24",
         "scaleDenominator": 33.3238997476528,
         "topLeftCorner": [-20037508.3427892, 20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16777216,
         "matrixHeight": 16777216
      }
   ]
}

....

One can define an arbitrary number of zoom levels. Here, 25 zoom levels are illustrated.

[[e.2-world-crs84-quad-tilematrixset-definition.]]
=== World CRS84 Quad TileMatrixSet definition.

[[e.2.1-world-crs84-quad-tilematrixset-definition.-xml-encoding]]
==== World CRS84 Quad TileMatrixSet definition. XML encoding

This is the XML definition of the WorldCRS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
      <TileMatrixSet xml:id="WorldCRS84Quad">
         <ows:Title>CRS84 for the World</ows:Title>
         <ows:Identifier>WorldCRS84Quad</ows:Identifier>
         <ows:BoundingBox crs="http://www.opengis.net/def/crs/OGC/1.3/CRS84">
            <ows:LowerCorner>-180 -90</ows:LowerCorner>
            <ows:UpperCorner>180 90</ows:UpperCorner>
         </ows:BoundingBox>
         <ows:SupportedCRS>
            http://www.opengis.net/def/crs/OGC/1.3/CRS84
         </ows:SupportedCRS>
         <WellKnownScaleSet>
            http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad
         </WellKnownScaleSet>
         <TileMatrix>
            <ows:Identifier>1</ows:Identifier>
            <ScaleDenominator>279541132.0143589</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>2</MatrixWidth>
            <MatrixHeight>1</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>2</ows:Identifier>
            <ScaleDenominator>139770566.0071794</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>4</MatrixWidth>
            <MatrixHeight>2</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>3</ows:Identifier>
            <ScaleDenominator>69885283.00358972</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>8</MatrixWidth>
            <MatrixHeight>4</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>4</ows:Identifier>
            <ScaleDenominator>34942641.50179486</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>16</MatrixWidth>
            <MatrixHeight>8</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>5</ows:Identifier>
            <ScaleDenominator>17471320.75089743</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>32</MatrixWidth>
            <MatrixHeight>16</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>6</ows:Identifier>
            <ScaleDenominator>8735660.375448715</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>64</MatrixWidth>
            <MatrixHeight>32</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>7</ows:Identifier>
            <ScaleDenominator>4367830.187724357</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>128</MatrixWidth>
            <MatrixHeight>64</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>8</ows:Identifier>
            <ScaleDenominator>2183915.093862179</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>256</MatrixWidth>
            <MatrixHeight>128</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>9</ows:Identifier>
            <ScaleDenominator>1091957.546931089</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>512</MatrixWidth>
            <MatrixHeight>256</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>10</ows:Identifier>
            <ScaleDenominator>545978.7734655447</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>1024</MatrixWidth>
            <MatrixHeight>512</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>11</ows:Identifier>
            <ScaleDenominator>272989.3867327723</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>2048</MatrixWidth>
            <MatrixHeight>1024</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>12</ows:Identifier>
            <ScaleDenominator>136494.6933663862</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>4096</MatrixWidth>
            <MatrixHeight>2048</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>13</ows:Identifier>
            <ScaleDenominator>68247.34668319309</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>8192</MatrixWidth>
            <MatrixHeight>4096</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>14</ows:Identifier>
            <ScaleDenominator>34123.67334159654</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>16384</MatrixWidth>
            <MatrixHeight>8192</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>15</ows:Identifier>
            <ScaleDenominator>17061.83667079827</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>32768</MatrixWidth>
            <MatrixHeight>16384</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>16</ows:Identifier>
            <ScaleDenominator>8530.918335399136</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>65536</MatrixWidth>
            <MatrixHeight>32768</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>17</ows:Identifier>
            <ScaleDenominator>4265.459167699568</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>131072</MatrixWidth>
            <MatrixHeight>65536</MatrixHeight>
         </TileMatrix>
         <TileMatrix>
            <ows:Identifier>18</ows:Identifier>
            <ScaleDenominator>2132.729583849784</ScaleDenominator>
            <TopLeftCorner>-180 90</TopLeftCorner>
            <TileWidth>256</TileWidth>
            <TileHeight>256</TileHeight>
            <MatrixWidth>262144</MatrixWidth>
            <MatrixHeight>131072</MatrixHeight>
         </TileMatrix>
      </TileMatrixSet>

....

 

[[e.2.2-world-crs84-quad-tilematrixset-definition.-json-encoding]]
==== World CRS84 Quad TileMatrixSet definition. JSON Encoding

This is the JSON definition of the WorldCRS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "CRS84 for the World",
   "identifier": "WorldCRS84Quad",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "lowerCorner": [-180, -90],
      "upperCorner": [180, 90]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
   "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 279541132.014358,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 1
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 139770566.007179,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 69885283.0035897,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 34942641.5017948,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 17471320.7508974,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 8735660.37544871,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 4367830.18772435,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 2183915.09386217,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 1091957.54693108,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 545978.773465544,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 272989.386732772,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 136494.693366386,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 68247.346683193,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 34123.6733415964,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 17061.8366707982,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 8530.91833539913,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 65536,
         "matrixHeight": 32768
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 4265.45916769956,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 131072,
         "matrixHeight": 65536
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 2132.72958384978,
         "topLeftCorner": [-180, 90],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 262144,
         "matrixHeight": 131072
      }
   ] 
}

....

[[e.3-world-mercator-wgs84-quad-tilematrixset-definition.]]
=== World Mercator WGS84 Quad TileMatrixSet definition.

[[e.3.1-world-mercator-wgs84-quad-tilematrixset-definition.-xml-encoding]]
==== World Mercator WGS84 Quad TileMatrixSet definition. XML encoding

This is the XML definition of the WorldMercatorWGS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
   <TileMatrixSet xml:id="WorldMercatorWGS84Quad">
      <ows:Title>World Mercator WGS84 (ellipsoid)</ows:Title>
      <ows:Identifier>WorldMercatorWGS84Quad</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/3395">
         <ows:LowerCorner>
            -20037508.3427892 -20037508.3427892
         </ows:LowerCorner>
         <ows:UpperCorner>
             20037508.3427892 20037508.3427892
         </ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
          http://www.opengis.net/def/crs/EPSG/0/3395
      </ows:SupportedCRS>
      <WellKnownScaleSet>
          http://www.opengis.net/def/wkss/OGC/1.0/WorldMercatorWGS84
      </WellKnownScaleSet>
      <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>559082264.028717</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1</MatrixWidth>
        <MatrixHeight>1</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>279541132.014358</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2</MatrixWidth>
        <MatrixHeight>2</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>139770566.007179</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>69885283.0035897</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>34942641.5017948</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16</MatrixWidth>
        <MatrixHeight>16</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>17471320.7508974</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32</MatrixWidth>
        <MatrixHeight>32</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>8735660.37544871</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>64</MatrixWidth>
        <MatrixHeight>64</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>4367830.18772435</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>128</MatrixWidth>
        <MatrixHeight>128</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>2183915.09386217</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>256</MatrixWidth>
        <MatrixHeight>256</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>1091957.54693108</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>512</MatrixWidth>
        <MatrixHeight>512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>545978.773465544</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1024</MatrixWidth>
        <MatrixHeight>1024</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>272989.386732772</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2048</MatrixWidth>
        <MatrixHeight>2048</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>136494.693366386</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4096</MatrixWidth>
        <MatrixHeight>4096</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>68247.346683193</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8192</MatrixWidth>
        <MatrixHeight>8192</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>34123.6733415964</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16384</MatrixWidth>
        <MatrixHeight>16384</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>17061.8366707982</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32768</MatrixWidth>
        <MatrixHeight>32768</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>16</ows:Identifier>
        <ScaleDenominator>8530.91833539913</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>65536</MatrixWidth>
        <MatrixHeight>65536</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>17</ows:Identifier>
        <ScaleDenominator>4265.45916769956</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>131072</MatrixWidth>
        <MatrixHeight>131072</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>18</ows:Identifier>
        <ScaleDenominator>2132.72958384978</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>262144</MatrixWidth>
        <MatrixHeight>262144</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>19</ows:Identifier>
        <ScaleDenominator>1066.36479192489</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>524288</MatrixWidth>
        <MatrixHeight>524288</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>20</ows:Identifier>
        <ScaleDenominator>533.182395962445</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1048576</MatrixWidth>
        <MatrixHeight>1048576</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>21</ows:Identifier>
        <ScaleDenominator>266.591197981222</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2097152</MatrixWidth>
        <MatrixHeight>2097152</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>22</ows:Identifier>
        <ScaleDenominator>133.295598990611</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4194304</MatrixWidth>
        <MatrixHeight>4194304</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>23</ows:Identifier>
        <ScaleDenominator>66.6477994953056</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8388608</MatrixWidth>
        <MatrixHeight>8388608</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>24</ows:Identifier>
        <ScaleDenominator>33.3238997476528</ScaleDenominator>
        <TopLeftCorner>-20037508.3427892 20037508.3427892</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16777216</MatrixWidth>
        <MatrixHeight>16777216</MatrixHeight>
      </TileMatrix>
    </TileMatrixSet>

....

 

One can define an arbitrary number of zoom levels. Here, 19 zoom levels are illustrated but resolutions up to 24 are currently available in some mass market services.

[[e.3.2-world-mercator-wgs84-quad-tilematrixset-definition.-json-encoding]]
==== World Mercator WGS84 Quad TileMatrixSet definition. JSON Encoding

This is the JSON definition of the WorldMercatorQuad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "World Mercator WGS84 (ellipsoid)",
   "identifier": "WorldMercatorWGS84Quad",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/3395",
      "lowerCorner": [-20037508.3427892, -20037508.3427892],
      "upperCorner": [20037508.3427892, 20037508.3427892]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3395",
   "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/WorldMercatorWGS84",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 559082264.028718,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1,
         "matrixHeight": 1
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 279541132.014358,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 139770566.007179,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 69885283.0035897,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 34942641.5017948,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 17471320.7508974,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 8735660.37544871,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 4367830.18772435,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 2183915.09386217,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 1091957.54693108,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 545978.773465544,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 272989.386732772,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 136494.693366386,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 68247.346683193,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 34123.6733415964,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 17061.8366707982,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 32768
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 8530.91833539913,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 65536,
         "matrixHeight": 65536
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 4265.45916769956,
         "topLeftCorner": [-20037508.3427892, -20037508.3427892],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 131072,
         "matrixHeight": 131072
      }
   ]
}

....

 

One can define an arbitrary number of zoom levels. Here, 19 zoom levels are illustrated but resolutions up to 24 are currently available in some mass market services.

 

[[e.4-universal-transverse-mercator-wgs84-quad-for-tilematrixset-definition-for-zone-31]]
=== Universal Transverse Mercator WGS84 Quad for TileMatrixSet definition for zone 31

[[e.4.1-utm-wgs84-quad-for-tilematrixset-definition-for-zone-31.-xml-encoding]]
==== UTM WGS84 Quad for TileMatrixSet definition for zone 31. XML encoding

This is the XML definition of the UTM31WGS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set if the zone 31 is required. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
    <TileMatrixSet xml:id="UTM31WGS84Quad">
      <ows:Title>Universal Transverse Mercator Zone 31 WGS84 Quad</ows:Title>
      <ows:Identifier>UTM31WGS84Quad</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/32631">
         <ows:LowerCorner>
            -9501965.72931276 -20003931.4586255
         </ows:LowerCorner>
         <ows:UpperCorner>
             10501965.7293128 20003931.4586255
         </ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
            http://www.opengis.net/def/crs/EPSG/0/32631
      </ows:SupportedCRS>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>279072704.500914</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1</MatrixWidth>
        <MatrixHeight>2</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>139536352.250457</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>69768176.1252285</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>34884088.0626143</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>16</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>17442044.0313071</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16</MatrixWidth>
        <MatrixHeight>32</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>8721022.01565356</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32</MatrixWidth>
        <MatrixHeight>64</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>4360511.00782678</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>64</MatrixWidth>
        <MatrixHeight>128</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>2180255.50391339</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>128</MatrixWidth>
        <MatrixHeight>256</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>1090127.7519567</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>256</MatrixWidth>
        <MatrixHeight>512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>545063.875978348</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>512</MatrixWidth>
        <MatrixHeight>1024</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>272531.937989174</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1024</MatrixWidth>
        <MatrixHeight>2048</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>136265.968994587</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2048</MatrixWidth>
        <MatrixHeight>4096</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>68132.9844972935</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4096</MatrixWidth>
        <MatrixHeight>8192</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>34066.4922486467</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8192</MatrixWidth>
        <MatrixHeight>16384</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>17033.2461243234</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16384</MatrixWidth>
        <MatrixHeight>32768</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>16</ows:Identifier>
        <ScaleDenominator>8516.62306216168</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32768</MatrixWidth>
        <MatrixHeight>65536</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>17</ows:Identifier>
        <ScaleDenominator>4258.31153108084</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>65536</MatrixWidth>
        <MatrixHeight>131072</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>18</ows:Identifier>
        <ScaleDenominator>2129.15576554042</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>131072</MatrixWidth>
        <MatrixHeight>262144</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>19</ows:Identifier>
        <ScaleDenominator>1064.57788277021</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>262144</MatrixWidth>
        <MatrixHeight>524288</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>20</ows:Identifier>
        <ScaleDenominator>532.288941385105</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>524288</MatrixWidth>
        <MatrixHeight>1048576</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>21</ows:Identifier>
        <ScaleDenominator>266.144470692553</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1048576</MatrixWidth>
        <MatrixHeight>2097152</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>22</ows:Identifier>
        <ScaleDenominator>133.072235346276</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2097152</MatrixWidth>
        <MatrixHeight>4194304</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>23</ows:Identifier>
        <ScaleDenominator>66.5361176731382</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4194304</MatrixWidth>
        <MatrixHeight>8388608</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>24</ows:Identifier>
        <ScaleDenominator>33.2680588365691</ScaleDenominator>
        <TopLeftCorner>-9501965.72931276 20003931.4586255</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8388608</MatrixWidth>
        <MatrixHeight>16777216</MatrixHeight>
      </TileMatrix>
    </TileMatrixSet>

....

 

[[e.4.2-utm-wgs84-quad-for-tilematrixset-definition-for-zone-31.-json-encoding]]
==== UTM WGS84 Quad for TileMatrixSet definition for zone 31. JSON Encoding

This is the JSON definition of the UTM31WGS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set if the zone 31 is required. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "UTM31WGS84Quad",
   "identifier": "Universal Transverse Mercator Zone 31 WGS84 Quad",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/32631",
      "lowerCorner":
      [
         -9501965.72931276,
         -20003931.4586255
      ],
      "upperCorner":
      [
         10501965.7293128,
         20003931.4586255
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/32631",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 279072704.500914,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 139536352.250457,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 69768176.1252285,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 34884088.0626143,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 17442044.0313071,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 8721022.01565356,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 4360511.00782678,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 2180255.50391339,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 1090127.7519567,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 545063.875978348,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 272531.937989174,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 136265.968994587,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 68132.9844972935,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 34066.4922486467,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 17033.2461243234,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 32768
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 8516.62306216168,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 65536
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 4258.31153108084,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 65536,
         "matrixHeight": 131072
      },
      {
         "type": "TileMatrixType",
         "identifier": "18",
         "scaleDenominator": 2129.15576554042,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 131072,
         "matrixHeight": 262144
      },
      {
         "type": "TileMatrixType",
         "identifier": "19",
         "scaleDenominator": 1064.57788277021,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 262144,
         "matrixHeight": 524288
      },
      {
         "type": "TileMatrixType",
         "identifier": "20",
         "scaleDenominator": 532.288941385105,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 524288,
         "matrixHeight": 1048576
      },
      {
         "type": "TileMatrixType",
         "identifier": "21",
         "scaleDenominator": 266.144470692553,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1048576,
         "matrixHeight": 2097152
      },
      {
         "type": "TileMatrixType",
         "identifier": "22",
         "scaleDenominator": 133.072235346276,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2097152,
         "matrixHeight": 4194304
      },
      {
         "type": "TileMatrixType",
         "identifier": "23",
         "scaleDenominator": 66.5361176731382,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4194304,
         "matrixHeight": 8388608
      },
      {
         "type": "TileMatrixType",
         "identifier": "24",
         "scaleDenominator": 33.2680588365691,
         "topLeftCorner":
         [
           -9501965.72931276,
           20003931.4586255
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8388608,
         "matrixHeight": 16777216
      }
   ]
}

....

 

[[e.5-arctic-universal-polar-stereographic-wgs-84-quad-tilematrixset-definition.]]
=== Arctic Universal Polar Stereographic WGS 84 Quad TileMatrixSet definition.

[[e.5.1-arctic-ups-wgs-84-quad-tilematrixset-definition.-xml-encoding]]
==== Arctic UPS WGS 84 Quad TileMatrixSet definition. XML encoding

This is the XML definition of the UPSArcticWGS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
    <TileMatrixSet xml:id="UPSArcticWGS84Quad">
      <ows:Title>Universal Polar Stereographic WGS 84 Quad for Arctic</ows:Title>
      <ows:Identifier>UPSArcticWGS84Quad</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/5041">
         <ows:LowerCorner>-14440759.350252 -14440759.350252</ows:LowerCorner>
         <ows:UpperCorner>18440759.350252 18440759.350252</ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
         http://www.opengis.net/def/crs/EPSG/0/5041
      </ows:SupportedCRS>
      <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>458726544.4</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1</MatrixWidth>
        <MatrixHeight>1</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>229363272.2</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2</MatrixWidth>
        <MatrixHeight>2</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>114681636.1</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>57340818.05</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>28670409.02</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16</MatrixWidth>
        <MatrixHeight>16</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>14335204.51</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32</MatrixWidth>
        <MatrixHeight>32</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>7167602.256</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>64</MatrixWidth>
        <MatrixHeight>64</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>3583801.128</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>128</MatrixWidth>
        <MatrixHeight>128</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>1791900.564</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>256</MatrixWidth>
        <MatrixHeight>256</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>895950.282</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>512</MatrixWidth>
        <MatrixHeight>512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>447975.141</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1024</MatrixWidth>
        <MatrixHeight>1024</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>223987.5705</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2048</MatrixWidth>
        <MatrixHeight>2048</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>111993.7852</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4096</MatrixWidth>
        <MatrixHeight>4096</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>55996.89262</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8192</MatrixWidth>
        <MatrixHeight>8192</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>27998.44631</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16384</MatrixWidth>
        <MatrixHeight>16384</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>13999.22316</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32768</MatrixWidth>
        <MatrixHeight>32768</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>16</ows:Identifier>
        <ScaleDenominator>6999.611578</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>65536</MatrixWidth>
        <MatrixHeight>65536</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>17</ows:Identifier>
        <ScaleDenominator>3499.805789</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>131072</MatrixWidth>
        <MatrixHeight>131072</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>18</ows:Identifier>
        <ScaleDenominator>1749.902894</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>262144</MatrixWidth>
        <MatrixHeight>262144</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>19</ows:Identifier>
        <ScaleDenominator>874.9514472</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>524288</MatrixWidth>
        <MatrixHeight>524288</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>20</ows:Identifier>
        <ScaleDenominator>437.4757236</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1048576</MatrixWidth>
        <MatrixHeight>1048576</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>21</ows:Identifier>
        <ScaleDenominator>218.7378618</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2097152</MatrixWidth>
        <MatrixHeight>2097152</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>22</ows:Identifier>
        <ScaleDenominator>109.3689309</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4194304</MatrixWidth>
        <MatrixHeight>4194304</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>23</ows:Identifier>
        <ScaleDenominator>54.68446545</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8388608</MatrixWidth>
        <MatrixHeight>8388608</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>24</ows:Identifier>
        <ScaleDenominator>27.34223273</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16777216</MatrixWidth>
        <MatrixHeight>16777216</MatrixHeight>
      </TileMatrix>
    </TileMatrixSet>

....

 

[[e.5.2-arctic-ups-wgs-84-quad-tilematrixset-definition.-json-enconding]]
==== Arctic UPS WGS 84 Quad TileMatrixSet definition. JSON enconding

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "ArcticUniversalPolarStereoWGS84Quad",
   "identifier": "Universal Polar Stereographic WGS 84 Quad for Arctic",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/5041",
      "lowerCorner":
      [
         -14440759.350252,
         -14440759.350252
      ],
      "upperCorner":
      [
         18440759.350252,
         18440759.350252
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/5041",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 458726544.4,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1,
         "matrixHeight": 1
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 229363272.2,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 114681636.1,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 57340818.05,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 28670409.02,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 14335204.51,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 7167602.256,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 3583801.128,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 1791900.564,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 895950.282,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 447975.141,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 223987.5705,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 111993.7852,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 55996.89262,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 27998.44631,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 13999.22316,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 32768
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 6999.611578,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 65536,
         "matrixHeight": 65536
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 3499.805789,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 131072,
         "matrixHeight": 131072
      },
      {
         "type": "TileMatrixType",
         "identifier": "18",
         "scaleDenominator": 1749.902894,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 262144,
         "matrixHeight": 262144
      },
      {
         "type": "TileMatrixType",
         "identifier": "19",
         "scaleDenominator": 874.9514472,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 524288,
         "matrixHeight": 524288
      },
      {
         "type": "TileMatrixType",
         "identifier": "20",
         "scaleDenominator": 437.4757236,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1048576,
         "matrixHeight": 1048576
      },
      {
         "type": "TileMatrixType",
         "identifier": "21",
         "scaleDenominator": 218.7378618,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2097152,
         "matrixHeight": 2097152
      },
      {
         "type": "TileMatrixType",
         "identifier": "22",
         "scaleDenominator": 109.3689309,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4194304,
         "matrixHeight": 4194304
      },
      {
         "type": "TileMatrixType",
         "identifier": "23",
         "scaleDenominator": 54.68446545,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8388608,
         "matrixHeight": 8388608
      },
      {
         "type": "TileMatrixType",
         "identifier": "24",
         "scaleDenominator": 27.34223273,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16777216,
         "matrixHeight": 16777216
      }
   ]
}

....

[[e.6-antarctic-universal-polar-stereographic-wgs84-quad-tilematrixset-definition.]]
=== Antarctic Universal Polar Stereographic WGS84 Quad TileMatrixSet definition.

[[e.6.1-antarctic-ups-wgs84-quad-tilematrixset-definition.-xml-encoding]]
==== Antarctic UPS WGS84 Quad TileMatrixSet definition. XML Encoding

This is the XML definition of the UPSAntarcticWGS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
    <TileMatrixSet xml:id="UPSAntarcticWGS84Quad">
      <ows:Title>Universal Polar Stereographic WGS 84 Quad for Antarctic</ows:Title>
      <ows:Identifier>UPSAntarcticWGS84Quad</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/5042">
         <ows:LowerCorner>-14440759.350252 -14440759.350252</ows:LowerCorner>
         <ows:UpperCorner>18440759.350252 18440759.350252</ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
         http://www.opengis.net/def/crs/EPSG/0/5042
      </ows:SupportedCRS>
      <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>458726544.4</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1</MatrixWidth>
        <MatrixHeight>1</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>229363272.2</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2</MatrixWidth>
        <MatrixHeight>2</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>114681636.1</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>57340818.05</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>28670409.02</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16</MatrixWidth>
        <MatrixHeight>16</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>14335204.51</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32</MatrixWidth>
        <MatrixHeight>32</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>7167602.256</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>64</MatrixWidth>
        <MatrixHeight>64</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>3583801.128</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>128</MatrixWidth>
        <MatrixHeight>128</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>1791900.564</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>256</MatrixWidth>
        <MatrixHeight>256</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>895950.282</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>512</MatrixWidth>
        <MatrixHeight>512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>447975.141</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1024</MatrixWidth>
        <MatrixHeight>1024</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>223987.5705</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2048</MatrixWidth>
        <MatrixHeight>2048</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>111993.7852</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4096</MatrixWidth>
        <MatrixHeight>4096</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>55996.89262</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8192</MatrixWidth>
        <MatrixHeight>8192</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>27998.44631</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16384</MatrixWidth>
        <MatrixHeight>16384</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>13999.22316</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32768</MatrixWidth>
        <MatrixHeight>32768</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>16</ows:Identifier>
        <ScaleDenominator>6999.611578</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>65536</MatrixWidth>
        <MatrixHeight>65536</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>17</ows:Identifier>
        <ScaleDenominator>3499.805789</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>131072</MatrixWidth>
        <MatrixHeight>131072</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>18</ows:Identifier>
        <ScaleDenominator>1749.902894</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>262144</MatrixWidth>
        <MatrixHeight>262144</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>19</ows:Identifier>
        <ScaleDenominator>874.9514472</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>524288</MatrixWidth>
        <MatrixHeight>524288</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>20</ows:Identifier>
        <ScaleDenominator>437.4757236</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1048576</MatrixWidth>
        <MatrixHeight>1048576</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>21</ows:Identifier>
        <ScaleDenominator>218.7378618</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2097152</MatrixWidth>
        <MatrixHeight>2097152</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>22</ows:Identifier>
        <ScaleDenominator>109.3689309</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4194304</MatrixWidth>
        <MatrixHeight>4194304</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>23</ows:Identifier>
        <ScaleDenominator>54.68446545</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8388608</MatrixWidth>
        <MatrixHeight>8388608</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>24</ows:Identifier>
        <ScaleDenominator>27.34223273</ScaleDenominator>
        <TopLeftCorner>-14440759.350252 18440759.350252</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16777216</MatrixWidth>
        <MatrixHeight>16777216</MatrixHeight>
      </TileMatrix>
    </TileMatrixSet>

....

 

[[e.6.2-antarctic-ups-wgs84-quad-tilematrixset-definition.-json-encoding]]
==== Antarctic UPS WGS84 Quad TileMatrixSet definition. JSON Encoding

This is the JSON definition of the UPSAntarcticWGS84Quad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "AntarcticUniversalPolarStereoWGS84Quad",
   "identifier": "Universal Polar Stereographic WGS 84 Quad for Antarctic",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/5042",
      "lowerCorner":
      [
         -14440759.350252,
         -14440759.350252
      ],
      "upperCorner":
      [
         18440759.350252,
         18440759.350252
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/5042",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 458726544.4,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1,
         "matrixHeight": 1
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 229363272.2,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 114681636.1,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 57340818.05,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 28670409.02,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 14335204.51,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 7167602.256,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 3583801.128,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 1791900.564,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 895950.282,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 447975.141,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 223987.5705,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 111993.7852,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 55996.89262,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 27998.44631,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 13999.22316,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 32768
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 6999.611578,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 65536,
         "matrixHeight": 65536
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 3499.805789,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 131072,
         "matrixHeight": 131072
      },
      {
         "type": "TileMatrixType",
         "identifier": "18",
         "scaleDenominator": 1749.902894,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 262144,
         "matrixHeight": 262144
      },
      {
         "type": "TileMatrixType",
         "identifier": "19",
         "scaleDenominator": 874.9514472,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 524288,
         "matrixHeight": 524288
      },
      {
         "type": "TileMatrixType",
         "identifier": "20",
         "scaleDenominator": 437.4757236,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1048576,
         "matrixHeight": 1048576
      },
      {
         "type": "TileMatrixType",
         "identifier": "21",
         "scaleDenominator": 218.7378618,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2097152,
         "matrixHeight": 2097152
      },
      {
         "type": "TileMatrixType",
         "identifier": "22",
         "scaleDenominator": 109.3689309,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4194304,
         "matrixHeight": 4194304
      },
      {
         "type": "TileMatrixType",
         "identifier": "23",
         "scaleDenominator": 54.68446545,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8388608,
         "matrixHeight": 8388608
      },
      {
         "type": "TileMatrixType",
         "identifier": "24",
         "scaleDenominator": 27.34223273,
         "topLeftCorner":
         [
           -14440759.350252,
           18440759.350252
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16777216,
         "matrixHeight": 16777216
      }
   ]
}

....

[[e.7-european-etrs89-laea-quad-tilematrixset-definition.]]
=== European ETRS89 LAEA Quad TileMatrixSet definition.

[[e.7.1-european-etrs89-laea-quad-tilematrixset-definition.-xml-encoding]]
==== European ETRS89 LAEA Quad TileMatrixSet definition. XML Encoding

This is the XML definition of the EuropeanETRS89_LAEAQuad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
    <TileMatrixSet xml:id="EuropeanETRS89_LAEAQuad">
      <ows:Title>Lambert Azimuthal Equal Area ETRS89 for Europe</ows:Title>
      <ows:Identifier>EuropeanETRS89_LAEAQuad</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/3035">
         <ows:LowerCorner>2000000.0 1000000.0</ows:LowerCorner>
         <ows:UpperCorner>6500000 5500000.0</ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
         http://www.opengis.net/def/crs/EPSG/0/3035
      </ows:SupportedCRS>
      <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>62779017.857142866</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1</MatrixWidth>
        <MatrixHeight>1</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>31389508.928571433</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2</MatrixWidth>
        <MatrixHeight>2</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>15694754.464285716</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4</MatrixWidth>
        <MatrixHeight>4</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>7847377.232142858</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>3923688.616071429</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16</MatrixWidth>
        <MatrixHeight>16</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>1961844.3080357146</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32</MatrixWidth>
        <MatrixHeight>32</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>980922.1540178573</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>64</MatrixWidth>
        <MatrixHeight>64</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>490461.07700892864</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>128</MatrixWidth>
        <MatrixHeight>128</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>245230.53850446432</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>256</MatrixWidth>
        <MatrixHeight>256</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>122615.26925223216</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>512</MatrixWidth>
        <MatrixHeight>512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>61307.63462611608</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1024</MatrixWidth>
        <MatrixHeight>1024</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>30653.81731305804</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2048</MatrixWidth>
        <MatrixHeight>2048</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>15326.90865652902</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4096</MatrixWidth>
        <MatrixHeight>4096</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>7663.45432826451</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8192</MatrixWidth>
        <MatrixHeight>8192</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>3831.727164132255</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>16384</MatrixWidth>
        <MatrixHeight>16384</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>1915.8635820661275</ScaleDenominator>
        <TopLeftCorner>2000000.0 5500000.0</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>32768</MatrixWidth>
        <MatrixHeight>32768</MatrixHeight>
      </TileMatrix>
    </TileMatrixSet>

....

 

[[e.7.2-european-etrs89-laea-quad-tilematrixset-definition.-json-encoding]]
==== European ETRS89 LAEA Quad TileMatrixSet definition. JSON Encoding

This is the JSON definition of the EuropeanETRS89_LAEAQuad tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "Lambert Azimuthal Equal Area ETRS89 for Europe",
   "identifier": "EuropeanETRS89_LAEAQuad",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/3035",
      "lowerCorner":
      [
         2000000.0,
         1000000.0
      ],
      "upperCorner":
      [
         6500000.0,
         5500000.0
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3035",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 62779017.8571428,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1,
         "matrixHeight": 1
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 31389508.9285714,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 2
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 15694754.4642857,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 4
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 7847377.23214285,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 3923688.61607142,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 16
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 1961844.30803571,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 32
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 980922.154017857,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 64
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 490461.077008928,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 128
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 245230.538504464,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 256,
         "matrixHeight": 256
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 122615.269252232,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 512,
         "matrixHeight": 512
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 61307.634626116,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1024,
         "matrixHeight": 1024
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 30653.817313058,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2048,
         "matrixHeight": 2048
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 15326.908656529,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4096,
         "matrixHeight": 4096
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 7663.45432826451,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8192,
         "matrixHeight": 8192
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 3831.72716413225,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16384,
         "matrixHeight": 16384
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 1915.86358206612,
         "topLeftCorner":
         [
           2000000.0,
           5500000.0
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32768,
         "matrixHeight": 32768
      }
   ]
}

....

 

[[e.8-canadian-lambert-conformal-conic-nad83-tilematrixset-definition.]]
=== Canadian Lambert Conformal Conic NAD83 TileMatrixSet definition.

[[e.8.1-canadian-lambert-conformal-conic-nad83-tilematrixset-definition.-xml-encoding]]
==== Canadian Lambert Conformal Conic NAD83 TileMatrixSet definition. XML Encoding

This is the XML definition of the CanadianNAD83_LCC tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,xml]
....
   <TileMatrixSet xml:id="CanadianNAD83_LCC">
      <ows:Title>Lambert Conformal Conic NAD83 for Canada</ows:Title>
      <ows:Identifier>CanadianNAD83_LCC</ows:Identifier>
      <ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/3978">
         <ows:LowerCorner>-7786476.885838887 -5153821.09213678</ows:LowerCorner>
         <ows:UpperCorner>7148753.233541353 7928343.534071138</ows:UpperCorner>
      </ows:BoundingBox>
      <ows:SupportedCRS>
         http://www.opengis.net/def/crs/EPSG/0/3978
       </ows:SupportedCRS>
      <TileMatrix>
        <ows:Identifier>0</ows:Identifier>
        <ScaleDenominator>137016643.080905</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>5</MatrixWidth>
        <MatrixHeight>5</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>1</ows:Identifier>
        <ScaleDenominator>80320101.1163925</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>8</MatrixWidth>
        <MatrixHeight>8</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>2</ows:Identifier>
        <ScaleDenominator>47247118.3037603</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>13</MatrixWidth>
        <MatrixHeight>14</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>3</ows:Identifier>
        <ScaleDenominator>28348270.9822562</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>21</MatrixWidth>
        <MatrixHeight>22</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>4</ows:Identifier>
        <ScaleDenominator>16536491.4063161</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>36</MatrixWidth>
        <MatrixHeight>38</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>5</ows:Identifier>
        <ScaleDenominator>9449423.66075207</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>62</MatrixWidth>
        <MatrixHeight>66</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>6</ows:Identifier>
        <ScaleDenominator>5669654.19645125</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>103</MatrixWidth>
        <MatrixHeight>110</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>7</ows:Identifier>
        <ScaleDenominator>3307298.28126323</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>177</MatrixWidth>
        <MatrixHeight>188</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>8</ows:Identifier>
        <ScaleDenominator>1889884.73215041</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>309</MatrixWidth>
        <MatrixHeight>329</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>9</ows:Identifier>
        <ScaleDenominator>1133930.83929025</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>515</MatrixWidth>
        <MatrixHeight>548</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>10</ows:Identifier>
        <ScaleDenominator>661459.656252643</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>882</MatrixWidth>
        <MatrixHeight>938</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>11</ows:Identifier>
        <ScaleDenominator>396875.793751586</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1470</MatrixWidth>
        <MatrixHeight>1563</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>12</ows:Identifier>
        <ScaleDenominator>236235.591518802</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2469</MatrixWidth>
        <MatrixHeight>2626</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>13</ows:Identifier>
        <ScaleDenominator>137016.643080905</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>4257</MatrixWidth>
        <MatrixHeight>4528</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>14</ows:Identifier>
        <ScaleDenominator>80320.1011163925</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>7262</MatrixWidth>
        <MatrixHeight>7723</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>15</ows:Identifier>
        <ScaleDenominator>47247.1183037603</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>12344</MatrixWidth>
        <MatrixHeight>13130</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>16</ows:Identifier>
        <ScaleDenominator>28348.2709822562</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>20574</MatrixWidth>
        <MatrixHeight>21882</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>17</ows:Identifier>
        <ScaleDenominator>16536.4914063161</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>35269</MatrixWidth>
        <MatrixHeight>37512</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>18</ows:Identifier>
        <ScaleDenominator>9449.42366075207</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>61720</MatrixWidth>
        <MatrixHeight>65646</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>19</ows:Identifier>
        <ScaleDenominator>5669.65419645125</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>102866</MatrixWidth>
        <MatrixHeight>109409</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>20</ows:Identifier>
        <ScaleDenominator>3307.29828126323</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>176341</MatrixWidth>
        <MatrixHeight>187558</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>21</ows:Identifier>
        <ScaleDenominator>1889.88473215041</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>308596</MatrixWidth>
        <MatrixHeight>328227</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>22</ows:Identifier>
        <ScaleDenominator>1133.93083929025</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>514327</MatrixWidth>
        <MatrixHeight>547044</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>23</ows:Identifier>
        <ScaleDenominator>661.459656252643</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>881703</MatrixWidth>
        <MatrixHeight>937790</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>24</ows:Identifier>
        <ScaleDenominator>396.875793751586</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>1469505</MatrixWidth>
        <MatrixHeight>1562983</MatrixHeight>
      </TileMatrix>
      <TileMatrix>
        <ows:Identifier>25</ows:Identifier>
        <ScaleDenominator>236.235591518802</ScaleDenominator>
        <TopLeftCorner>-34655800 39310000</TopLeftCorner>
        <TileWidth>256</TileWidth>
        <TileHeight>256</TileHeight>
        <MatrixWidth>2468768</MatrixWidth>
        <MatrixHeight>2625811</MatrixHeight>
      </TileMatrix>
   </TileMatrixSet>

....

 

[[e.8.2-canadian-lambert-conformal-conic-nad83-tilematrixset-definition.-json-encoding]]
==== Canadian Lambert Conformal Conic NAD83 TileMatrixSet definition. JSON Encoding

This is the JSON definition of the CanadianNAD83_LCC tile matrix set that can be reproduced by other standards needing to define a tile matrix set. Not all TileMatrix elements need to be included and including other TileMatrices for more detailed scales is possible if they follow the same pattern.

[source,JSON]
....
{
   "type": "TileMatrixSetType",
   "title": "Lambert conformal conic NAD83 for Canada",
   "identifier": "CanadianNAD83_LCC",
   "boundingBox":
   {
      "type": "BoundingBoxType",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/3978",
      "lowerCorner":
      [
         -7786476.885838887,
         -5153821.09213678
      ],
      "upperCorner":
      [
         7148753.233541353,
         7928343.534071138
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3978",
   "tileMatrices":
   [
      {
         "type": "TileMatrixType",
         "identifier": "0",
         "scaleDenominator": 145000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 5,
         "matrixHeight": 5
      },
      {
         "type": "TileMatrixType",
         "identifier": "1",
         "scaleDenominator": 85000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 8
      },
      {
         "type": "TileMatrixType",
         "identifier": "2",
         "scaleDenominator": 50000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 13,
         "matrixHeight": 14
      },
      {
         "type": "TileMatrixType",
         "identifier": "3",
         "scaleDenominator": 30000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 21,
         "matrixHeight": 22
      },
      {
         "type": "TileMatrixType",
         "identifier": "4",
         "scaleDenominator": 17500000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 36,
         "matrixHeight": 38
      },
      {
         "type": "TileMatrixType",
         "identifier": "5",
         "scaleDenominator": 10000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 62,
         "matrixHeight": 66
      },
      {
         "type": "TileMatrixType",
         "identifier": "6",
         "scaleDenominator": 6000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 103,
         "matrixHeight": 110
      },
      {
         "type": "TileMatrixType",
         "identifier": "7",
         "scaleDenominator": 3500000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 177,
         "matrixHeight": 188
      },
      {
         "type": "TileMatrixType",
         "identifier": "8",
         "scaleDenominator": 2000000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 309,
         "matrixHeight": 329
      },
      {
         "type": "TileMatrixType",
         "identifier": "9",
         "scaleDenominator": 1200000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 515,
         "matrixHeight": 548
      },
      {
         "type": "TileMatrixType",
         "identifier": "10",
         "scaleDenominator": 700000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 882,
         "matrixHeight": 938
      },
      {
         "type": "TileMatrixType",
         "identifier": "11",
         "scaleDenominator": 420000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1470,
         "matrixHeight": 1563
      },
      {
         "type": "TileMatrixType",
         "identifier": "12",
         "scaleDenominator": 250000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2469,
         "matrixHeight": 2626
      },
      {
         "type": "TileMatrixType",
         "identifier": "13",
         "scaleDenominator": 145000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4257,
         "matrixHeight": 4528
      },
      {
         "type": "TileMatrixType",
         "identifier": "14",
         "scaleDenominator": 85000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 7262,
         "matrixHeight": 7723
      },
      {
         "type": "TileMatrixType",
         "identifier": "15",
         "scaleDenominator": 50000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 12344,
         "matrixHeight": 13130
      },
      {
         "type": "TileMatrixType",
         "identifier": "16",
         "scaleDenominator": 30000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 20574,
         "matrixHeight": 21882
      },
      {
         "type": "TileMatrixType",
         "identifier": "17",
         "scaleDenominator": 17500,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 35269,
         "matrixHeight": 37512
      },
      {
         "type": "TileMatrixType",
         "identifier": "18",
         "scaleDenominator": 10000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 61720,
         "matrixHeight": 65646
      },
      {
         "type": "TileMatrixType",
         "identifier": "19",
         "scaleDenominator": 6000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 102866,
         "matrixHeight": 109409
      },
      {
         "type": "TileMatrixType",
         "identifier": "20",
         "scaleDenominator": 3500,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 176341,
         "matrixHeight": 187558
      },
      {
         "type": "TileMatrixType",
         "identifier": "21",
         "scaleDenominator": 2000,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 308596,
         "matrixHeight": 328227
      },
      {
         "type": "TileMatrixType",
         "identifier": "22",
         "scaleDenominator": 1200,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 514327,
         "matrixHeight": 547044
      },
      {
         "type": "TileMatrixType",
         "identifier": "23",
         "scaleDenominator": 700,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 881703,
         "matrixHeight": 937790
      },
      {
         "type": "TileMatrixType",
         "identifier": "24",
         "scaleDenominator": 420,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 1469505,
         "matrixHeight": 1562983
      },
      {
         "type": "TileMatrixType",
         "identifier": "25",
         "scaleDenominator": 250,
         "topLeftCorner":
         [
           -34655800,
           39310000
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2468768,
         "matrixHeight": 2625811
      }
   ]
}

....
