[appendix]
[[annex_g]]
[[example-encodings-for-json-ld-informative]]
:appendix-caption: Annex
== Example encodings for JSON-LD  (Informative)

This informative Annex provides an example of JSON-LD TileMatrixSet2D and the corresponding result in RDF Turtle.

[[json-ld-document-instance]]
=== JSON-LD document instance

Example of JSON-LD document instance. @context documents have been included when necessary and the identifiers have been qualified with a namespace ensuring a good transformation to RDF using a JSON-LD engine. The complete example can be found in the supplemental material described in Annex B.

[source,json]
....
{
   "@context": ["http://localhost/json-ld/tms-context.json", {"example": "http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/"}],
   "title": "CRS84 for the World",
   "identifier": "example:",
   "boundingBox":
   {
      "@context": "http://localhost/json-ld/tms-boundingbox-context.json",
      "@id": "example:BoundingBox",
      "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "lowerLeft":
      [
         -180,
         -90
      ],
      "upperRight":
      [
         180,
         90
      ]
   },
   "supportedCRS": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
   "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad",
   "tileMatrices":
   [
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:0",
         "scaleDenominator": 279541132.014358,
         "topLeftCorner":
         [
           -180,
           90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 2,
         "matrixHeight": 1
      },
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:1",
         "scaleDenominator": 139770566.007179,
         "topLeftCorner":
         [
           -180,
           90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 4,
         "matrixHeight": 2
      },
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:2",
         "scaleDenominator": 69885283.0035897,
         "topLeftCorner":
         [
           -180,
            90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 8,
         "matrixHeight": 4
      },
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:3",
         "scaleDenominator": 34942641.5017948,
         "topLeftCorner":
         [
           -180,
           90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 16,
         "matrixHeight": 8
      },
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:4",
         "scaleDenominator": 17471320.7508974,
         "topLeftCorner":
         [
           -180,
           90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 32,
         "matrixHeight": 16
      },
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:5",
         "scaleDenominator": 8735660.37544871,
         "topLeftCorner":
         [
           -180,
           90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 64,
         "matrixHeight": 32
      },
      {
         "@context": "http://localhost/json-ld/tms-tilematrix-context.json",
         "identifier": "example:6",
         "scaleDenominator": 4367830.18772435,
         "topLeftCorner":
         [
            -180,
           90
         ],
         "tileWidth": 256,
         "tileHeight": 256,
         "matrixWidth": 128,
         "matrixHeight": 64
      }
   ]
}

....

 

[[n3-turtle-document]]
=== N3 turtle document

This document has been automatically generated by the JSON-DL Playground (https://json-ld.org/playground/) by providing the document in subsection G.1 as input. The complete example can be found in the supplemental material described in Annex B.

[source,RDF]
....
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.opengis.net/tms/2.0/matrixHeight> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.opengis.net/tms/2.0/matrixWidth> "2"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.opengis.net/tms/2.0/scaleDenominator> "2.79541132014358E8"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b7 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.opengis.net/tms/2.0/matrixHeight> "2"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.opengis.net/tms/2.0/matrixWidth> "4"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.opengis.net/tms/2.0/scaleDenominator> "1.39770566007179E8"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b9 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.opengis.net/tms/2.0/matrixHeight> "4"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.opengis.net/tms/2.0/matrixWidth> "8"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.opengis.net/tms/2.0/scaleDenominator> "6.98852830035897E7"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b11 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.opengis.net/tms/2.0/matrixHeight> "8"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.opengis.net/tms/2.0/matrixWidth> "16"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.opengis.net/tms/2.0/scaleDenominator> "3.49426415017948E7"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b13 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.opengis.net/tms/2.0/matrixHeight> "16"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.opengis.net/tms/2.0/matrixWidth> "32"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.opengis.net/tms/2.0/scaleDenominator> "1.74713207508974E7"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b15 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.opengis.net/tms/2.0/matrixHeight> "32"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.opengis.net/tms/2.0/matrixWidth> "64"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.opengis.net/tms/2.0/scaleDenominator> "8.735660375448709E6"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b17 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.opengis.net/tms/2.0/matrixHeight> "64"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.opengis.net/tms/2.0/matrixWidth> "128"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.opengis.net/tms/2.0/scaleDenominator> "4.36783018772435E6"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.opengis.net/tms/2.0/tileHeight> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.opengis.net/tms/2.0/tileWidth> "256"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.opengis.net/tms/2.0/topLeftCorner> _:b19 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/> <http://www.opengis.net/tms/2.0/boundingBox> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/BoundingBox> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/> <http://www.opengis.net/tms/2.0/supportedCRS> <http://www.opengis.net/def/crs/OGC/1.3/CRS84> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/> <http://www.opengis.net/tms/2.0/tileMatrix> _:b0 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/> <http://www.opengis.net/tms/2.0/title> "CRS84 for the World" .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/> <http://www.opengis.net/tms/2.0/wellKnownScaleSet> <http://www.opengis.net/def/wkss/OGC/1.0/GoogleCRS84Quad> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/TileMatrixSetType> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/BoundingBox> <http://www.opengis.net/tms/2.0/crs> <http://www.opengis.net/def/crs/OGC/1.3/CRS84> .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/BoundingBox> <http://www.opengis.net/tms/2.0/lowerLeft> _:b21 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/BoundingBox> <http://www.opengis.net/tms/2.0/upperRight> _:b23 .
<http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/BoundingBox> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.opengis.net/tms/2.0/BoundingBoxType> .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/0> .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1 .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/1> .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b2 .
_:b10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b12 .
_:b12 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b12 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b13 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b13 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b14 .
_:b14 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b14 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b15 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b15 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b16 .
_:b16 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b16 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b17 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b17 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b18 .
_:b18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b19 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b19 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b20 .
_:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/2> .
_:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b3 .
_:b20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b21 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b21 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b22 .
_:b22 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b22 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b23 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b23 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b24 .
_:b24 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b24 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/3> .
_:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b4 .
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/4> .
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b5 .
_:b5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/5> .
_:b5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b6 .
_:b6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <http://www.opengis.net/tms/2.0/example/WorldCRS84Quad/6> .
_:b6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b8 .
_:b8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "9.0E1"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:b9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "-1.8E2"^^<http://www.w3.org/2001/XMLSchema#double> .
_:b9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b10 .

....


[[json-ld-context-document-example]]
=== JSON-LD @context document example

This is the tms-context.json document that is included at the beginning of a JSON TileMatrixSet2D instance to transform it into a JSON-LD file. Other similar @context documents are included in other sections and are provided as supplementary material to this document as explained in Annex B.

[source,json]
....
{
   "@context":
   {
      "tms": "http://www.opengis.net/tms/2.0/",
      "identifier": "@id",
      "type": "@type",
      "title": "tms:title",
      "abstract": "tms:abstract",
      "boundingBox": "tms:boundingBox",
      "TileMatrixSetType": "tms:TileMatrixSetType",
      "supportedCRS":
      {
         "@id": "tms:supportedCRS",
         "@type": "@id"
      },
      "wellKnownScaleSet":
      {
         "@id": "tms:wellKnownScaleSet",
         "@type": "@id"
      },
      "tileMatrices":
      {
         "@id": "tms:tileMatrix",
         "@container": "@list"
      }
   }
}

....
 
