[appendix]
[[annex_f]]
[[example-encodings-for-tilesetmetadata-informative]]
:appendix-caption: Annex
== Example encodings for TileSetMetadata (Informative)

This informative Annex provides an example of use for TileSetMetadata and TileMatrixSetLimits2D data structures.

[[json-document-instance-using-tilesetmetadata]]
=== JSON document instance using TileSetMetadata

TileSetMetadata data structure can be used for a resource to specify the tiling schema the resource supports. Eventually, the resource can only be available in a fragment of the tiled space and to specify that, the TileMatrixSetLimits2D data structure is populated. This example illustrates and instance encoded in JSON.

[source,json]
....
include::../schemas/tms/2.0/json/examples/tileset/tiles.WebMercatorQuad.json[]
....
 
[[json-schema-used-to-validate-the-previous-json-document]]
=== JSON schema used to validate the previous JSON document

The TileSetMetadata data structure can be included in the definition of a resource data model. This JSON Schema fragment illustrates how this standard JSON schemas can be used in conjunction with the resource schemas.

[source,json]
....
include::../schemas/tms/2.0/json/tileSet.json[]
....

[[xml-document-instance-using-tilesetmetadata]]
=== XML document instance using TileSetMetadata

TileSetMetadata data structure can be used for a resource to specify the tiling schema the resource supports. Eventually, the resource can only be available in a fragment of the tiled space and to specify that, the TileMatrixSetLimits2D data structure is populated. This example illustrates and instance encoded in XML.

[source,xml]
....
include::../schemas/tms/2.0/xml/examples/tileset/tiles.WebMercatorQuad.xml[]
....

[[xml-schema-used-to-validate-the-previous-xml-document]]
=== XML schema used to validate the previous XML document

The TileSetMetadata data structure can be included in the definition of a resource data model. This XML Schema fragment illustrates how this standard XML schemas can be used in conjunction with the resource schemas.

[source,xml]
....
include::../schemas/tms/2.0/xml/tileset.xsd[]
....
