[[tileset-metadata-encodings]]
== TileSetMetadata encodings

[[tsmd-json-encoding]]
=== JSON encoding
The JSON encoding has been done respecting the naming and types of the original classes.

[[json-encoding-of-a-tilematrixsetlimits]]
==== JSON TileMatrixSetLimits

include::requirements/requirements_json-tilematrixsetlimits.adoc[]

include::requirements/json-tilematrixsetlimits/REQ_json_tilematrixsetlimits_model.adoc[]

include::requirements/json-tilematrixsetlimits/REQ_json_tilematrixsetlimits_ietf.adoc[]

include::requirements/json-tilematrixsetlimits/REQ_json_tilematrixsetlimits_schema.adoc[]

NOTE: A TileMatrixSetLimits description can be embedded within the TileSetMetadata, as for the _OGC API - Tiles_ tileset conformance class.

<<example-encodings-for-tilesetmetadata-informative>> provides JSON examples for common TileMatrixSetLimits.

[[json-encoding-of-a-tilesetmetadata]]
==== JSON TileSetMetadata

include::requirements/requirements_json-tilesetmetadata.adoc[]

include::requirements/json-tilesetmetadata/REQ_json_tilesetmetadata_model.adoc[]

include::requirements/json-tilesetmetadata/REQ_json_tilesetmetadata_ietf.adoc[]

include::requirements/json-tilesetmetadata/REQ_json_tilesetmetadata_schema.adoc[]

NOTE: A TileSetMetadata description can be embedded in other file formats, such as a Service Metadata document of a WMTS service. In this case, the media type of the containing document prevails.

<<example-encodings-for-tilesetmetadata-informative>> provides JSON examples encoding TileSetMetadata.

The encoding of PropertySchema adopts the JSON Schema form starting by and element propertiesSchema that defines the GeoJSON element "properties" for this layer (the composition of "properties" is undefined by GeoJSON but it can be define for a layer instance if its features follow a data model). <<propertiesSchema-attributes-JSON-Schema-quivalences>> describes the mapping between the FeatureAttribute class attributes (in <<parts-of-feature-attribute-data-structure>>) and the JSON schema properties.

[#propertiesSchema-attributes-JSON-Schema-quivalences,reftext='{table-caption} {counter:table-num}']
.propertiesSchema attributes and JSON Schema properties equivalences
[width = "100%",options="header"]
|===
| .propertiesSchema attributes | JSON Schema properties
| title | title
| keywords | N/A
| identifier | name of the additional property
| type | combination of 'type' and 'format'
| pattern | pattern
| mediaType | contentMediaType
| acceptedValues | enum
| range | a combination of 'maximum', 'exclusiveMaximum', 'minimum' and 'exclusiveMinimum'
| lowerMultiplicity | minItems
| upperMultiplicity |  maxItems
| observedProperty | N/A
| observedPropertyURI | N/A
| uom | N/A
| uomURI | N/A
|===

[[tsmd-xml-encoding]]
=== XML encoding
The XML encoding has been done respecting the naming and types of the original classes. However all attribute names have been transformed to UpperCamelCase.

[[xmltilematrixsetlimits-requirements-class]]
==== XML TileMatrixSetLimits

include::requirements/requirements_xml-tilematrixsetlimits.adoc[]

include::requirements/xml-tilematrixsetlimits/REQ_xml_tilematrixsetlimits_model.adoc[]

include::requirements/xml-tilematrixsetlimits/REQ_xml_tilematrixsetlimits_schema.adoc[]

NOTE: A TileMatrixSetLimits is normally used as embedded in other XML documents. That is the reason an associated media type is not provided.

<<example-encodings-for-tilesetmetadata-informative>> provides XML examples encoding TileMatrixSetLimits.

[[xml-tileset-metadata]]
==== XML TileSetMetadata

include::requirements/requirements_xml-tilesetmetadata.adoc[]

include::requirements/xml-tilesetmetadata/REQ_xml_tilesetmetadata_model.adoc[]

include::requirements/xml-tilesetmetadata/REQ_xml_tilesetmetadata_schema.adoc[]

NOTE: A TileSetMetadata does not currently have an associated media type.

<<example-encodings-for-tilesetmetadata-informative>> provides XML examples encoding TileSetMetadata.
