[[terms-and-definitions]]
== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply:

*4.1*           

*cell*

minimum geometrical spaces delimited by the grid lines of a regular grid.

NOTE: in 2D spaces, cells are often referred as pixels.

NOTE: In this standard, the term _pixel_ is reserved to the individual elements of a visualization device. Tiles are composed by regular grid cells that can be made partially coincident with the pixels of a visualization device for display purposes.

*4.2*

*coordinate reference system*

coordinate system that is related to the real world by a datum [ISO 19111]

*4.3*           

*coordinate system*

set of mathematical rules for specifying how coordinates are to be assigned to points [ISO 19111]

*4.4*           

*domain*

well-defined set [ISO/TS 19103:2005]

NOTE: A mathematical function may be defined on this set, i.e. in a function f:A–>B, A is the domain of the function f.

*4.5*           

*grid*

network composed of two or more sets of curves in which the members of each set intersect the members of the other sets in an algorithmic way [ISO 19123:2005]

NOTE: The curves partition a space into grid cells.

NOTE: A grid can be used to define a tessellation of the space.

*4.6*           

*range set*

set of all values a function f can take as its arguments vary over its domain [OGC 07-036]

*4.7*           

*raster tile*

tile that contains information in a gridded form. Commonly the values of the grid represent colors of each cell in the grid for immediate pictorial representation on visualization devices, but can also be coverage subsets.

NOTE: This concept is used in this standard as a contraposition of "vector tiles". Many of the existing implementations of WMTS 1.0 produce "raster tiles".

*4.8*           

*regular grid*

grid whose grid lines have a constant distance along each grid axis [OGC 09-146r6]

NOTE: A regular grid can be used to define a regular tessellation of the space.

*4.9*

*space partitioning*

process of dividing a geometric space (usually a Euclidean space) into two or more disjoint subsets (see also partition of a set). Space partitioning divides a space into non-overlapping regions. Any point in the space can then be identified to lie in exactly one of the regions [OGC 19-014r3]

*4.10*

*square*

regular quadrilateral with four equal sides and four 90 degree angles [OGC 19-014r3]

*4.11*

*tessellation*

partitioning of a space into a set of conterminous subspaces having the same dimension as the space being partitioned [ISO 19123]

NOTE: A tessellation composed of congruent regular polygons or polyhedra is a regular tessellation. One composed of regular, but non-congruent polygons or polyhedra is a semi-regular tessellation. Otherwise the tessellation is irregular.

*4.12*           

*tile*

geometric shape with known properties that may or may not be the result of a tiling (tessellation) process. A tile consists of a single connected "piece" (topological disc) without "holes" or "lines" [OGC 19-014r3] +
+
small rectangular representation of geographic data, often part of a set of such elements, covering a tiling scheme and sharing similar information content and graphical styling. A tile can be uniquely defined in a tile matrix by one integer index in each dimension. Tiles are mainly used for fast transfer (particularly in the web) and easy display at the resolution of a visualization device. Tiles can be grid based pictorial representations, coverage subsets, or feature based representations (e.g., vector tiles).

*4.13*        

*tile matrix*

grid tile scheme that defines how space is partitioned into a set of conterminous tiles at a fixed scale.

NOTE: A tile matrix constitutes a tessellation of the space that resembles a matrix in a 2D space characterized by a matrix width (columns) and a matrix height (rows).

NOTE: In this standard, a tile matrix is not used alone and it is part of time matrix set.

*4.14*        

*tile matrix set*

tile scheme composed by collection of tile matrices defined at different scales covering approximately the same area and have a common coordinate reference system.

*4.15*        

*tile scheme*

scheme that defines the unique properties of each individual tile in a tile set. These properties include a unique identifier for each tile, the tile origin, and the extent of the tile.

NOTE: A tile scheme is not restricted to a coordinate reference system or a tile matrix set and allows for other spatial reference systems such as DGGS and other organizations including irregular ones.

*4.16*        

*tile set*

set of tiles - a collection of subsets of the space being partitioned. [OGC 19-014r3]+
+
series of actual tiles contain data and following a common tiling scheme.

*4.17*        

*tile set metadata*

additional metadata beyond the common properties defining the tile set. Such metadata could be an abstract, the owner, the author, or other common metadata. [OGC 19-014r3]+
+
metadata describing common properties defining a tile set, layers and styles used to produce the tile set, the limits of the time matrix with actual data and common metadata such as abstract, owner, author, etc.

*4.18*        

*vector tile*

tile that contains geometric features information that has been simplified at the tile scale resolution and clipped by the tile boundaries.

NOTE: The expression "vector tile" has associated some controversy in the OGC. Actually, the OGC uses geometrical features to refer to things that are commonly knows as vectors in many GIS tools. However, in this case, this standard recognizes the level fo penetration of the expression in the sector and assumes that the concept is not associated to any particular technology or commercial brand.

*4.19*        

*well-known scale set*

well-known combination of a coordinate reference system and a set of scales that a tile matrix set declares support for
