
[[xml-encoding]]
== XML encoding

[[xmltilematrixset2d-requirements-class]]
=== XMLTileMatrixSet2D requirements class

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/xml-tilematrixset2d.

include::requirements/REQ_xml_tilematrixset2d_model.adoc[]

include::requirements/REQ_xml_tilematrixset2d_schema.adoc[]

include::requirements/REQ_xml_tilematrixset2d_media-type.adoc[]

NOTE: A TileMatrixSet2D description can be embedded in other file formats, such as a Service Metadata document of a WMTS service. In this case, the media type of the containing document prevails.

Annex E provides XML examples for common TileMatrixSet2D.

[[xmltilematrixsetlimits2d-requirements-class]]
=== XMLTileMatrixSetLimits2D requirements class

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/xml-tilematrixsetlimits2d.

include::requirements/REQ_xml_tilematrixsetlimits2d_model.adoc[]

include::requirements/REQ_xml_tilematrixsetlimits2d_schema.adoc[]

NOTE: A TileMatrixSetLimits2D description is normally used as embedded in other XML documents. That is the reason an associated media type is not provided.

Annex F provides XML examples for common TileMatrixSetLimits2D.

[[xml-tilematrixsetlink2d]]
=== XML TileMatrixSetLink2D

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/xml-tilematrixsetlink2d.

include::requirements/REQ_xml_tilematrixsetlink2d_model.adoc[]

include::requirements/REQ_xml_tilematrixsetlink2d_schema.adoc[]

NOTE: A TileMatrixSetLink2D description is normally used as embedded in other XML documents. That is the reason an associated media type is not provided.

Annex F provides XML examples for common TileMatrixSetLink2D.

[[xml-variablematrixwitdh]]
=== XML VariableMatrixWitdh

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/xml-variablematrixwidth.

include::requirements/REQ_xml_variablematrixwidth_model.adoc[]

include::requirements/REQ_xml_variablematrixwidth_schema.adoc[]

Annex H provides XML examples for common VariableMatrixWidth
