[[json-encoding]]
== JSON encoding

The JSON encoding has been done respecting the naming and types of the original classes. However, there are some differences.  <<class-attributes-JSON-element-quivalences>> describes some exceptions in the mapping between the class attributes and corresponding JSON element.

[#class-attributes-JSON-element-quivalences,reftext='{table-caption} {counter:table-num}']
.propertiesSchema attributes and JSON Schema properties equivalences
[width = "100%",options="header"]
|===
| Class attribute | JSON element | Reason
| identifier | id | Following come practice in GeoJSON and JSON-LD
| BoundingBox class | array of 4 numbers representing lowerLeft and topRight coordinates | Following GeoJSON suggested encoding
| LanguageString | string | JSON files are general used in the OGC API as monolingual documents. The language of the document is determined by the HTTP language negotiation headers
|===

[[jsontilematrixset2d]]
=== JSONTileMatrixSet2D

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/json-tilematrixset2d.

include::requirements/REQ_json_tilematrixset2d_model.adoc[]

include::requirements/REQ_json_tilematrixset2d_ietf.adoc[]

include::requirements/REQ_json_tilematrixset2d_schema.adoc[]

include::requirements/REQ_json_tilematrixset2d_media-type.adoc[]


NOTE: A TileMatrixSet2D description can be embedded in other file formats, such as a Service Metadata document of a WMTS service. In this case, the media type of the containing document prevails.

Annex E provides JSON examples for common TileMatrixSet2D.


[[json-encoding-of-a-tilematrixsetlimits]]
=== JSON encoding of a TileMatrixSetLimits

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/json-tilematrixsetlimits2d.

include::requirements/REQ_json_tilematrixsetlimits2d_model.adoc[]

include::requirements/REQ_json_tilematrixsetlimits2d_ietf.adoc[]

include::requirements/REQ_json_tilematrixsetlimits2d_schema.adoc[]

NOTE: A TileMatrixSetLimits2D description can be embedded in other file formats, such as a Service Metadata document of a WMTS service. In this case, the media type of the containing document prevails.

Annex F provides JSON examples for common TileMatrixSet2DLimits.

[[json-encoding-of-a-tilematrixsetlink]]
=== JSON encoding of a TileSetMetadata

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/json-tilematrixsetlink2d.

include::requirements/REQ_json_tilesetmetadata2D_model.adoc[]

include::requirements/REQ_json_tilesetmetadata2D_ietf.adoc[]

include::requirements/REQ_json_tilesetmetadata2D_schema.adoc[]

NOTE: A TileSetMetadata2D description can be embedded in other file formats, such as a Service Metadata document of a WMTS service. In this case, the media type of the containing document prevails.

Annex F provides JSON examples for common TileMatrixSet2DLink.

The encoding of propertiesSchema adopts the JSON Schema form. <<propertiesSchema-attributes-JSON-Schema-quivalences>> describes the mapping between the FeatureAttributes class attributes (in <<parts-of-feature-attribute-data-structure>>) and the JSON schema properties.

[#propertiesSchema-attributes-JSON-Schema-quivalences,reftext='{table-caption} {counter:table-num}']
.propertiesSchema attributes and JSON Schema properties equivalences
[width = "100%",options="header"]
|===
| .propertiesSchema attributes | JSON Schema properties
| title | title
| abstract | description
| keywords | N/A
| identifier | name of the additional property
| type | combination of 'type' and 'format'
| pattern | pattern
| mediaType | contentMediaType
| acceptedValues | enum
| range | a combination of 'maximum', 'exclusiveMaximum', 'minimum' and 'exclusiveMinimum'
| lowerMultiplicity | minItems
| upperMultiplicity |  maxItems
| observedProperty | N/A
| observedPropertyURI | N/A
| uom | N/A
| uomURI | N/A
|===

[[json-variablematrixwitdh]]
=== JSON VariableMatrixWitdh

The identifying URI for this class is http://www.opengis.net/spec/tilematrixset/1.0/req/json-variablematrixwidth.

include::requirements/REQ_json_variablematrixwidth_model.adoc[]

include::requirements/REQ_json_variablematrixwidth_ietf.adoc[]

include::requirements/REQ_json_variablematrixwidth_schema.adoc[]

Annex H provides JSON examples for common VariableMatrixWidth.
