[[tileset-metadata-encodings]]
== TileSetMetadata encodings

[[tsmd-json-encoding]]
=== JSON encoding

[[json-encoding-of-a-tilematrixsetlimits]]
==== JSON TileMatrixSetLimits2D

The identifying URI for this class is http://www.opengis.net/spec/tms/2.0/req/json-tilematrixsetlimits2d.

include::requirements/REQ_json_tilematrixsetlimits2d_model.adoc[]

include::requirements/REQ_json_tilematrixsetlimits2d_ietf.adoc[]

include::requirements/REQ_json_tilematrixsetlimits2d_schema.adoc[]

NOTE: A TileMatrixSetLimits2D description can be embedded within the TileSetMetadata, as for the _OGC API - Tiles_ tileset conformance class.

Annex G provides JSON examples for common TileMatrixSetLimits2D.

[[json-encoding-of-a-tilesetmetadata]]
==== JSON TileSetMetadata

The identifying URI for this class is http://www.opengis.net/spec/tms/2.0/req/json-tilesetmetadata.

include::requirements/REQ_json_tilesetmetadata_model.adoc[]

include::requirements/REQ_json_tilesetmetadata_ietf.adoc[]

include::requirements/REQ_json_tilesetmetadata_schema.adoc[]

NOTE: A TileSetMetadata description can be embedded in other file formats, such as a Service Metadata document of a WMTS service. In this case, the media type of the containing document prevails.

Annex G provides JSON examples encoding TileSetMetadata.

The encoding of propertiesSchema adopts the JSON Schema form. <<propertiesSchema-attributes-JSON-Schema-quivalences>> describes the mapping between the FeatureAttributes class attributes (in <<parts-of-feature-attribute-data-structure>>) and the JSON schema properties.

[#propertiesSchema-attributes-JSON-Schema-quivalences,reftext='{table-caption} {counter:table-num}']
.propertiesSchema attributes and JSON Schema properties equivalences
[width = "100%",options="header"]
|===
| .propertiesSchema attributes | JSON Schema properties
| title | title
| abstract | description
| keywords | N/A
| identifier | name of the additional property
| type | combination of 'type' and 'format'
| pattern | pattern
| mediaType | contentMediaType
| acceptedValues | enum
| range | a combination of 'maximum', 'exclusiveMaximum', 'minimum' and 'exclusiveMinimum'
| lowerMultiplicity | minItems
| upperMultiplicity |  maxItems
| observedProperty | N/A
| observedPropertyURI | N/A
| uom | N/A
| uomURI | N/A
|===

[[tsmd-xml-encoding]]
=== XML encoding

[[xmltilematrixsetlimits2d-requirements-class]]
==== XML TileMatrixSetLimits2D

The identifying URI for this class is http://www.opengis.net/spec/tms/2.0/req/xml-tilematrixsetlimits2d.

include::requirements/REQ_xml_tilematrixsetlimits2d_model.adoc[]

include::requirements/REQ_xml_tilematrixsetlimits2d_schema.adoc[]

NOTE: A TileMatrixSetLimits2D is normally used as embedded in other XML documents. That is the reason an associated media type is not provided.

Annex G provides XML examples encoding TileMatrixSetLimits2D.

[[xml-tileset-metadata]]
==== XML TileSetMetadata

The identifying URI for this class is http://www.opengis.net/spec/tms/2.0/req/xml-tilesetmetadata.

include::requirements/REQ_xml_tilesetmetadata_model.adoc[]

include::requirements/REQ_xml_tilesetmetadata_schema.adoc[]

NOTE: A TileSetMetadata does not currently have an associated media type.

Annex G provides XML examples encoding TileSetMetadata.
