[[terms-and-definitions]]
== Terms and Definitions

This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply:

*4.1*           

*coordinate reference system*

coordinate system that is related to the real world by a datum [ISO 19111]

*4.2*           

*coordinate system*

set of mathematical rules for specifying how coordinates are to be assigned to points [ISO 19111]

*4.3*           

*domain*

well-defined set [ISO/TS 19103:2005]

NOTE: A mathematical function may be defined on this set, i.e. in a function f:A–>B, A is the domain of the function f.

*4.4*           

*grid*

network composed of two or more sets of curves in which the members of each set intersect the members of the other sets in an algorithmic way [ISO 19123:2005]

NOTE: The curves partition a space into grid cells.

NOTE: A grid can be used to define a tessellation of the space.

*4.5*           

*range set*

set of all values a function f can take as its arguments vary over its domain [OGC 07-036]

*4.6*           

*raster tile*

a tile that contains information in a gridded form. Commonly the values of the grid represent colors of each cell in the grid for immediate pictorial representation on rendering devices, but can also be coverage subsets.

*4.7*           

*regular grid*

grid whose grid lines have a constant distance along each grid axis [OGC 09-146r6]

NOTE: A regular grid can be used to define a regular tessellation of the space.

*4.8*           

*tessellation*

partitioning of a space into a set of conterminous subspaces having the same dimension as the space being partitioned [ISO 19123]

NOTE: A tessellation composed of congruent regular polygons or polyhedra is a regular tessellation. One composed of regular, but non-congruent polygons or polyhedra is a semi-regular tessellation. Otherwise the tessellation is irregular.

*4.9*           

*tile*

a small rectangular representation of geographic data, often part of a set of such elements, covering a tiling scheme and sharing similar information content and graphical styling. A tile can be uniquely defined in a tile matrix by one integer index in each dimension. Tiles are mainly used for fast transfer (particularly in the web) and easy display at the resolution of a rendering device. Tiles can be grid based pictorial representations, coverage subsets, or feature based representations (e.g., vector tiles).

*4.10*        

*tile matrix*

a grid tiling scheme that defines how space is partitioned into a set of conterminous tiles at a fixed scale.

NOTE A tile matrix constitutes a tessellation of the space that resembles a matrix in a 2D space characterized by a matrix width (columns) and a matrix height (rows).

*4.11*        

*tile matrix set*

a tiling scheme composed by collection of tile matrices defined at different scales covering approximately the same area and has a common coordinate reference system.

*4.12*        

*tiling scheme*

a scheme that defines how space is partitioned into individual tiled units. A tiling scheme defines the spatial reference system, the geometric properties of a tile, which space a uniquely identified tile occupies, and reversely, which unique identifier corresponds to a space satisfying the geometric properties to be a tile.

NOTE: A tiling scheme is not restricted to a coordinate reference system or a tile matrix set and allows for other spatial reference systems such as DGGS and other organizations including irregular ones.

*4.13*        

*tile set*

a series of actual tiles contain data and following a common tiling scheme.

*4.14*        

*vector tile*

a tile that contains vector information that has been simplified at the tile scale resolution and clipped by the tile boundaries.

*4.15*        

*well-known scale set*

a well-known combination of a coordinate reference system and a set of scales that a tile matrix set declares support for
