== Scope

This document specifies the concepts of a tile matrix set and tile set metadata and their implementation in 2D space. This standard also provides both a XML and a JSON encoding.

The Tile Matrix Set concept, initially developed in OGC Web Map Tile Service (WMTS) 1.0, is now provided as an independent standard that can be referenced by other standards such as _OGC API - Tiles_, _OGC GeoPackage_, _OGC CDB_ or the Natural Resources Canada (NRCan)-promoted specification _Map Markup Language (MapML)_. In addition, this standard ensures that the tile matrix set concept can be used to tile both gridded as well as vector data.

This document also contains an informative annex for <<annex-common-tilematrixset-definitions-informative>> with a library of proposed tile matrix set definitions for Mercator, Transverse Mercator, Polar Stereographic, Lambert Azimuthal Equal Area, and Lambert Conformal Conic.
An additional annex for <<annex-variable-tilematrixset-definitions-informative>> provides tile matrix sets definitions utilizing the variable width capabilities of this standard allowing to roughly approximate equal area tiles for Plate Carrée projections.

Global identifiers for the Tile Matrix Sets defined in these annexes are registered with the OGC Naming Authority in the http://www.opengis.net/def/tms[Tile Matrix Set Register].

The Tile Set Metadata provides information about the intended usage of a Tile Set as well as the origin, security level, tiling scheme, layers and feature properties contained within. A tile set is a series of tiles containing data and following a common tiling scheme. Tile Set Metadata is intended to facilitate retrieval of tile sets and describes the major characteristics of tile sets without actually accessing the tiles nor the content contained in a tile. The Tile set Metadata was initially developed in phase two of the OGC Vector Tiles Pilot.

NOTE: A previous version of this standard had a JSON-LD encoding of the classes presented in <<tilematrixset2d-model>>. This encoding was abandoned as no interest was detected.
