
[[ats_tilesetmetadata_identifier]]
[abstract_test]
====
[%metadata]
label:: /conf/tilematrixsetmetadata/identifier

subject:: <<req_tilesetmetadata_identifier>>

test-purpose:: Validate that a tiled resource or dataset declares support to a tile
matrix set by one of the following two methods: a link to a tile matrix set
definition (e.g. one of the TileMatrixSet definitions from
<<annex-common-tilematrixset-definitions-informative>> or
<<annex-variable-tilematrixset-definitions-informative>>) as one of the links in the
links list, or by explicitly including a TileMatrixSet definition (as an object in
the `tileMatrixSet` property).

[.component,class=test-method]
--
Validate the requirements of the model

Test passes if a tiled resource or dataset declares support to a tile matrix set by
one of the following two methods: a link to a tile matrix set definition (including
the TileMatrixSet definition from
<<annex-common-tilematrixset-definitions-informative>> and
<<annex-example-encodings-for-variable-matrix-width-informative>>) as one of the
links in the links list or by explicitly including a TileMatrixSet definition (as an
object in the `tileMatrixSet` property).
--
====