[abstract]
== Abstract

The OGC Tile Matrix Set Standard defines the rules and requirements for a tile matrix
set as a way to index space based on a set of regular grids defining a domain (tile
matrix) for a limited list of scales in a Coordinate Reference System (CRS) as
defined in <<ogc08-005r4>> Abstract Specification Topic 2: Referencing by
Coordinates. This content was initially included in <<ogc07-057r7>> OpenGIS Web Map
Tile Service Implementation Standard (WMTS) and was separated in the <<ogc17-083r2>>
OGC Two Dimensional Tile Matrix Set, to allow reusability in other data formats of
services that need a tiling scheme. This document is a revision of the
<<ogc17-083r2>> and the general tile matrix set concept is inherited from it with
small additions. In a tile matrix set, each tile matrix is divided into regular
tiles. In a tile matrix set, a tile can be univocally identified by a tile column, a
tile row, and a tile matrix identifier. The OGC Tile Matrix Set Standard describes a
data structure defining the properties of the tile matrix set in both UML diagrams
and in tabular form. This document also defines a new data structure, called tile set
metadata, that can be used to describe a particular set of tiles following a tile
matrix set. XML and JSON encodings are described both for tile matrix sets and tile
matrix set metadata. It includes tile matrix set limits, links to the tile matrix
set, details of the original data represented by the tile set and a nice point of
origin to start exploring the tile set. Finally, the document offers practical
examples of tile matrix sets both for common global projections and for specific
regions.

== Preface

In 2007 the OGC approved and released the Web Map Tile Service Standard
<<ogc07-057r7>> (WMTS). WMTS defines "tile matrix set". Over time, other OGC
standards with requirements for "tiles" or tiled structures needed to use the same
definition. Unfortunately, other OGC standards could not use the tile matrix set
definition directly because the definition was formally linked to the tile service.
This revision uncouples the concept of a tile matrix set from the WMTS standard so
that other standards can reference the concept directly. This version of the standard
also provides an informative list of commonly used tile matrix sets and ensures
consistency with the <<ogc19-014r3>> OGC Abstract Specification Topic 22 - Core
Tiling Conceptual and Logical Models for 2D Euclidean Space. This document is
anticipated to impact and inform future revisions of other OGC Standards such as
GeoPackage and CDB and be used in future formats and services needing tiles for
storage or parallel processing.

Attention is drawn to the possibility that some of the elements of this document may
be the subject of patent rights. The Open Geospatial Consortium shall not be held
responsible for identifying any or all such patent rights.

_Recipients of this document are requested to submit, with their comments,
notification of any relevant patent claims or other intellectual property rights of
which they may be aware that might be infringed by any implementation of the standard
set forth in this document, and to provide supporting documentation._

== Security Considerations

The correct definition of a tile matrix set and the availability of tile set metadata
are crucial to be able to correctly geo-reference a tile. The use of the wrong tile
matrix set could result in incorrect geo-referencing of the tiles and the features
represented in those tiles. In an emergency situation, such such incorrect
referencing could result in sending first responders to the wrong location.

In a normal service interaction, the client requests the tile matrix set once and
requests one or more tiles afterwards. The client needs to ensure that the tile
matrix set definition has not been tampered with and corresponds to the correct tile
matrix set. In practice this means that the client and server must use a mechanism to
ensure that the service is really what it claims to be and that the message that
travels from the server to the client has not been altered.

If a server points to a definition of a tile matrix set that is hosted elsewhere, in
addition to the precautions stated above, the client must ensure that the service
providing the definition of the tile matrix set is a trusted service. In addition,
the synchronization of the tiles and the tile matrix set definition need to be
ensured, guaranteeing that the tile matrix set definition has not been updated
afterwards without the tile service knowing it.

== Submitters

All questions regarding this submission should be directed to the editor or the
submitters:

[cols="a,a",options="header,unnumbered"]
|===
| Name | Affiliation

| Joan Maso | Universitat Autonoma de Barcelona (UAB-CREAF)
| Jeff Yutzler | Image Matters LLC
| Peter Rushforth | Canada Centre for Mapping and Earth Observation, Natural Resources Canada
| Jérôme St-Louis | Ecere Corporation
| Jeff Harrison | US Army Geospatial Center

|===
