
[[annex-example-encodings-for-variable-matrix-width-informative]]
[appendix,obligation="informative"]
== Example encodings for Variable Matrix Width TileMatrixSets

This informative Annex provides examples of encodings for tile matrix
sets using the Variable Matrix Width requirements class.

=== GNOSIS Global Grid

These are the JSON and XML definitions of the GNOSISGlobalGrid tile
matrix set (see <<gnosis-global-grid-tilematrixset-definition>>)
that can be reproduced by other standards needing to define a tile
matrix set. Not all TileMatrix elements need to be included and including
other TileMatrices for more detailed scales is possible if they follow
the same pattern.

One can define an arbitrary number of zoom levels. Here, 5 zoom levels
are illustrated.

[[json-gnosisglobalgrid]]
==== GNOSIS Global Grid (JSON encoding)

The complete JSON example can be found in the supplemental material
described in <<annex-schema-documents-normative>>

[source,json]
----
include::../schemas/tms/2.0/json/examples/tilematrixset/GNOSISGlobalGrid.json[lines=1..90]
      }
   ]
}
----

[[xml-gnosisglobalgrid]]
==== GNOSIS Global Grid (XML encoding)

[source,xml,options="unnumbered"]
----
include::../schemas/tms/2.0/xml/examples/tilematrixset/GNOSISGlobalGrid.xml[lines=1..80]
</TileMatrixSet>
----

=== CDB 1 Global Grid

These are the JSON and XML definitions of the CDB1GlobalGrid tile
matrix set (see <<cdb-global-grid-tilematrixset-definition>>)
that can be reproduced by other standards needing to define a tile
matrix set. Not all TileMatrix elements need to be included and including
other TileMatrice for more detailed scales is possible if they follow
the same pattern.

One can define an arbitrary number of zoom levels. Here, 3 zoom levels
are illustrated.


[[json-cdb1globalgrid]]
==== CDB 1 Global Grid (JSON encoding)

[source,json]
----
include::../schemas/tms/2.0/json/examples/tilematrixset/CDB1GlobalGrid.json[lines=1..7]
include::../schemas/tms/2.0/json/examples/tilematrixset/CDB1GlobalGrid.json[lines=215..282]
      }
   ]
}
----
 

[[xml-cdb1globalgrid]]
==== CDB 1 Global Grid (XML encoding)

[source,xml,options="unnumbered"]
----
include::../schemas/tms/2.0/xml/examples/tilematrixset/CDB1GlobalGrid.xml[lines=1..9]
include::../schemas/tms/2.0/xml/examples/tilematrixset/CDB1GlobalGrid.xml[lines=190..249]
</TileMatrixSet>
----
