
[bibliography]
== Bibliography

* [[[ogc07-036, OGC 07-036]]]

* [[[ogc17-041, OGC 17-041]]]

* [[[ogc06-042, OGC 06-042]]]

* [[[dengler,3]]], Dengler K., Heinen T., Huber A., Molch, K., Mikusch  E.: The EOC
Geoservice: Standardized Access to Earth Observation Data Sets and Value Added
Products. PV 2013, 4.-6.Nov. 2013, Frascati, Italy. http://elib.dlr.de/86351

* [[[dgiwg, 4]]], DGIWG 124 Defence Profile of OGC Web Map Tile Service 1.0, 17
October 2017. https://portal.dgiwg.org/files/?artifact_id=68271&format=pdf

* [[[wmtsg, 5]]], Digital Globe: Web Map Tile Service Developer Guide. Cloud Services | August 2013.
https://dg-cms-uploads-production.s3.amazonaws.com/uploads/document/file/174/DGCS_DeveloperGuide_WMTS.pdf

* [[[dlr, 6]]], DLR: Geospatial Web Services Lists of services and their current
status. https://geoservice.dlr.de/web/services#tilecache

* [[[ogc20-040r3, OGC 20-040r3]]]

* [[[ogc20-092, OGC 20-092]]]

* [[[ogc19-088r2, OGC 19-088r2]]]

* [[[ogc18-076, OGC 18-076]]]

* [[[ogc18-025, OGC 18-025]]]

* [[[mapbox, 12]]], MapBox: MBTiles Specification.
https://github.com/mapbox/mbtiles-spec

* [[[ogc19-069, OGC 19-069]]]

* [[[ogc07-057r7, OGC 07-057r7]]]

* [[[ogc13-082r2, OGC 13-082r2]]]

* [[[ogc18-086r1, OGC 18-086r1]]]

* [[[ogc05-077r4, OGC 05-077r4]]]

* [[[nga-web, 18]]], NGA: Implementation Practice Web Mercator Map Projection.
NGA.SIG.0011_1.0_WEBMERC, https://nsgreg.nga.mil/doc/view?i=4105

* [[[nga-map, 19]]], NGA: Map Projections for Tiled Raster Graphics,
NGA.SIG.0014_1.0_PROJRAS, V. 1.0, 24 April 2015 https://nsgreg.nga.mil/doc/view?i=1810

* [[[nga-mercator, 20]]], NGA, Mercator-Addendum, Map Projections for Tiled Raster
Graphics Addendum for the Mercator Projection, NGA.SIG.0014_1.0_PROJRAS, V. 0.2,
2016-05-17

* [[[nga-nsg, 21]]], NGA, National System for Geospatial-Intelligence (NSG) Web Map
Tile Service 1.0.0 Interoperability Standard NGA.STND.0063_1.1_WMTS, 2018-04-27

* [[[nga-ups, 22]]], NGA: UPS-Amendment, Map Projections for Tiled Raster Graphics
Amendment for Universal Polar Stereographic, NGA.SIG.0014_1.0_PROJRAS, V. 0.1,
2016-06-03.

* [[[nga-grids, 23]]], NGA: The Universal Grids and the Transverse Mercator and Polar
Stereographic Map Projections, NGA.SIG.0012_2.0.0_UTMUPS, V. 2.0.0, 25 March 2014.
https://nsgreg.nga.mil/doc/view?i=4106

* [[[ogc15-113r5, OGC 15-113r5]]]

* [[[rollins, 26]]], Rollins C. and Paniccia M.: National Geospatial-Intelligence
Agency ESRI Users Conference, July 22, 2015.
https://www.slideshare.net/NGA_GEOINT/ngas-position-on-webmercator

* [[[snyder, 27]]], Snyder J. P.:  Map projections: A working manual. Professional
Paper 1395. By:. https://pubs.usgs.gov/pp/1395/report.pdf

* [[[stefanakis, 28]]], Stefanakis, E.: Web Mercator Projection & Raster Tile Maps.
Two cornerstones of Online Map Service Providers. Annual Conference - 2017 - Ottawa,
May 31- June 2, 2017.
http://www2.unb.ca/~estef/talks/CCA2017_Technical_Session_Stefanakis.pdf

* [[[ogc19-082r1, OGC 19-082r1]]]

* [[[ogc18-078, OGC 18-078]]]

* [[[ogc18-083, OGC 18-083]]]

* [[[ogc12-128r17, OGC 12-128r17]]]

* [[[ogc18-101, OGC 18-101]]]

* [[[rfc4287, IETF RFC 4287]]]

* [[[rfc6838, IETF RFC 6838]]]
