[[Clause_Critical]]
== Description of Critical Changes

=== Identifying with `uri` a well-known TileMatrixSet in the official OGC registry
A TileMatrixSet registered on the official OGC NA TileMatrixSets registry now identifies itself as such with a `uri` property pointing the canonical definition.

=== Replacing `topLeftCorner` by `pointOfOrigin`
The `topLeftCorner` property is replaced by `pointOfOrigin` to reflect the fact that tile matrix rows can now be counted starting from the bottom (based on the enumeration value of `cornerOfOrigin` property).

=== Renaming `supportedCRS` to `crs`
The `supportedCRS` property was renamed to the more appropriate `crs`, since it identifies the one CRS in which the TileMatrixSet is defined.
Additionally, a new clause clarifies the compatibility between a TileSet CRS and its TileMatrixSet CRS, facilitating the re-use of common registered TileMatrixSets.

=== JSON encoding rules to derive a JSON encoding from UML
Some extra rules for deriving JSON encodings from UML that results in a more natural output were introduced.

As a result, some properties were renamed. For example in the JSON encoding, `identifier` was renamed to `id`, and `tileMatrix` was renamed to the plural `tileMatrices` (since its value is an array).

=== Data model for tileset metadata
In version 1.0 there was a concept of TileMatrixSetLink (and data structure) designed to allow a dataset to declare the use of a tile matrix set defined elsewhere and, if needed, a limited coverage for this tile matrix set. In this standard, this concept has been extended beyond recognition into the TileSetMetadata structure that contains the metadata describing a set of tiles representing the same geospatial data and all conforming to a tile matrix set (a tileset), the limited coverage, and the suggested center point. Even if the new data structure looks different and covers more use cases, the previous functionality provided by the TileMatrixSetLink data structure is still included in the TileSetMetadata structure.

Equivalences from the old version into the new version are:

[#Equivalences-old-new-data-structures,reftext='{table-caption} {counter:table-num}']
.Equivalences between the old and new data structures
[width = "100%",options="header"]
|===
| Previous version (1.0) | Current version (2.0)
| TileMatrixSetLink | TileSetMetadata
| |
|===

=== Linking to (rel: `tiling-scheme`) or embedding a TileMatrixSet definition, and identifying use of registered TileMatrixSet with `tileMatrixSetURI`
A `tileMatrixSetURI` is now used for the tileset metadata to reference a TileMatrixSet registered on the official OGC NA TileMatrixSets registry.
In addition, either a link to a TileMatrixSet (using a `rel`=tiling-scheme), or a embedded TileMatrixSet definition (for offline use cases) must be provided.
This link can be either to an official OGC NA TileMatrixSet definition, or to the server's own local definition (e.g. at `/tileMatrixSets/{tileMatrixSetID}`).
