[[Clause_Substantive]]
== Description of Substantive Changes
This section enumerates the main changes done from the previous version of this Standard which are significant, but do not affect backward compatibility.
If only for these changes, unmodified existing clients would have been able to use existing TileMatrixSet definitions without any changes.
However, since this version also introduces <<Clause_Critical,critical changes>>, both clients (consumers) and servers (producers) will require modifications
to conform to the new version, and the encodings of the previous version will not validate against the schemas of this new version, and vice-versa.

=== Align with the Abstract specification Topic 22
Significant effort has been done to align the terminology with the Abstract specification Topic 22 - Core Tiling Conceptual and Logical Models for 2D Euclidean Space OGC 19-014r3. The most significant addition is the "tile set concept" ("set of tiles - a collection of subsets of the space being partitioned. [OGC 19-014r3]").

=== OWS Common dependency removed
We removed the dependency to OWS common and imported the necessary element in the document instead: LanguageString, Description Title Keyword data elements and Bounding Box.

=== Allowing embedded WKT2 CRS definition in addition to CRS by reference
In this version of the standard, the possibility to define a CRS using a full description in addition to a reference to an external CRS catalogue is introduced. For backwards compatibility, CRSType still defaults to a URI but is extended to a union of three possibilities (URI, WKT2 CRS, or ISO 19115 MD_ReferenceSystem).

=== Adding `cellSize` and `cornerOfOrigin`
The `cellSize` of a tile matrix is added to complement the existing `scaleDenominator` of a tile matrix. They are related by the use of the standard 0.28mm pixel size so they are complementary. `cornerOfOrigin` was added to allow for bottom-left origin of the tile rows indices, in addition to the common top-left.

=== Making `boundingBox` optional
The `boundingBox` property was made optional, highlighting the fact that the space occupied by tiles is really defined by the `pointOfOrigin` as well as the `scaleDenominator` / `resolution`, and the `matrixWidth` and `matrixHeight` of *each* TileMatrix, not the `boundingBox` of the overall TileMatrixSet.
Examples were updated to not define the bounding box, which should not be relied upon by clients.

=== Adding optional `orderedAxes` to highlight CRS axis ordering
An optional `orderedAxes` property can be used to highlight the axis ordering of the TileMatrixSet's CRS without having to look up the CRS definition.
It should also help avoid mistakes where the axis ordering used for specifying the TileMatrices `pointOfOrigin` is inconsistent with the CRS axis ordering.
However, this property cannot be used to modify the axis ordering defined by the CRS. Examples were updated to include this property.

=== Removing `type` object properties
The `type` property of the JSON encoding (e.g. `TileMatrixSetType`) were removed, as they were superfluous because wherever it was used, each property
could only be of a s single type (no polymorphism is required). Additionnally, it was agreed that when such `type` property would be used in future specifications,
the enumeration values would avoid a `Type` suffix.

=== Removing the JSON-LD
Due to the lack of interest and concerns on real use cases the JSON-LD encoding was removed. It can be reintroduced at later stage if there is demand.

=== XML and JSON encoding for tileset metadata
An XML and JSON encoding for tileset metadata was included. The JSON encoding will likely constitute a basis for the upcoming _OGC API - Tiles_ specification's _TileSet_ conformance class.

=== New annex with variable width TileMatrixSets definitions
This new Annex E includes the description of variable width TileMatrixSets that complements some already existing examples which have been moved to the Annex G. It also mentions a possible relationship to axis-aligned DGGS.

=== Added example encodings of CDB 1 variable width TileMatrixSet
JSON and XML definitions of the CDB 1 tile matrix set are added to Annex G as another example of Variable width tile matrix sets.

=== New annex with consideration for Extending TileMatrixSets for additional dimensions
The informative Annex J proposes approaches for extending TileMatrixSets and TileSet metadata for indexing and accessing 3D, 4D and n-D (n > 2) data as tiles, regardless of whether a simple file-based data store, a database (e.g. a GeoPackage) or a web API is used. All of these approaches assume that the multi-dimensional content spans the two dimensions defined by 2D TileMatrixSets, which are usually either latitude and longitude for geographic CRSes, or X/Easting or Y/Northing for projected CRSes, as well as other extra dimensions.
